### ISSUE TITLE
 PST verbal constants should only be audible

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1053]
They contain text not in tags, so now we print this garbage to the message window. Eg.:
```
@46009 = ~Nameless One Action 2 1~ [NAM032]
```

`Actor::VerbalConstant` should disable printing in PST. You can check for it with `core->HasFeature(GF_FLOATING_TEXT)`.

**Comment by chilvence** [comment]
Hmm, I chased it to here, and disabling the first if statement stops it spamming the message window:

https://github.com/gemrb/gemrb/blob/bb2515f815f9905e96990dfe7eb326a47056b9ae/gemrb/core/GameScript/GSUtils.cpp#L503-L511

I think it's probably safe to assume that no text was ever destined to show up in the message window via this method, since it is always closed, does that seem fair?

**Comment by lynxlynxlynx** [comment]
Ignoring DS_CONSOLE sounds like a good first attempt.

**Comment by chilvence** [comment]
I think the flag is supposed to be GF_ONSCREEN_TEXT

Does this look alright? 

https://github.com/gemrb/gemrb/commit/8d54623c5a737210bfb99820a398c160b33d3f6c

**Comment by lynxlynxlynx** [comment]
Yep. Sound is still ok, right?

**Comment by chilvence** [comment]
Yes, selection feedback still works (so I assume everything else will)
