### ISSUE TITLE
 [IWD/HOW/Trials] the party members are slowly fading at the beginning of trials of the luremaster

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1107]
#### Bug description
the party members are slowly fading at the beginning of trials of the luremaster during battle with harpies until they are invisible

GemRB version: master (SDL2), OK with subviews (SDL2, with or without OGL)

#### Steps to reproduce
1. Talk to Hobart (ar9101 [1017.470]),
2. during battle with harpies, members are slowly fading

**Comment by fizzet** [comment]
If this doesn't manifest on subviews, there is another problem there. The real issue here is with `fx_transparency_modifier` from `spin181`. The effect description on IESDP seems incomplete at best, so I'm not entirely sure what is actually supposed to happen, but our current implementation seems faulty.

**Comment by bradallred** [comment]
I don't know what could be wrong on subviews. `fx_transparency_modifier` just modifies `IE_TRANSLUCENT` and I can hardcode that in `Actor::Draw` and get the expected result drawn so the rendering capability for it works fine.

**Comment by fizzet** [comment]
I haven't actually looked at subviews, tbh, but the effect is clearly broken. This video (https://www.youtube.com/watch?v=nEo04h3_tt0), at 26:10, shows what's supposed to happen. I have a naive implementation that handles this particular situation just fine, but it modifies the base stat instead of modified because it needs to keep state, and that leaves me with a couple of additional questions:

1. Is this the right way to go about things?
2. How do multiple (possibly conflicting) effects of this type interact?
3. Do they ever wear out? How and when?

At the moment, we're adding two conflicting permanent (!) effects to an actor every time spin181 is cast on it. I could imagine that a plain set is actually supposed to expire immediately, a fade when it reaches 0%/100% transparency, and possibly any time another transparency effect is applied. That quite likely means the timing mode needs to be taken into account.

But even if that is true, it doesn't quite answer what happens if you don, say, an item that sets a flat 50% transparency and then apply a permanent fade like the spell does. Does the item get ignored? Is the fade ignored? Does the item set the bounds for the fade?

**Comment by lynxlynxlynx** [comment]
The cutscenes and area script do nothing, so yeah, it's all in the spell. There's no conflict with the two inverse opcodes, since the fade-in one is delayed (both are permanent). If both were to evaluate in the same tick, both would take effect, so the order matters — same for combos with equipping effects.

We should be taking duration into account to determine fade speed instead of just halving it. Can't really do it here, but I think 1 round (as in the first effect and video) is what they used (or at least as the fallback). That might fix this spell on its own.

**Comment by fizzet** [comment]
Is that theoretical, or from an actual engine run? Because my (theoretical) interpretation of the effects in the spell would be different.

To me they read like "fade out by 8" and "fade in by 8", respectively. Note that fade speed is actually an effect parameter, and we cannot simply rewrite the parameters like we do at the moment. The value 8 here actually matches pretty nicely with what you see in the video. It would also mean that those two effects simply cancelled each other out if they fired at the same time, no matter the application order.

And why would you want to keep "spent" permanent effects around? That seems like a really bad idea, and I'll also note that is not how fx_strength_modifier and friends handle permanency.

In any case, the STAT_MOD at the end misuses param2 and needs fixing up. (Those parameter-less macros are really good at hiding bugs like that...)

**Comment by lynxlynxlynx** [comment]
8 out of 256 is negligible; for a speed it would have to be at least 45 or have a special meaning to match the video, so I'm inclined to trust the reverse engineered explanation for that parameter ("fade amount" not speed).

I agree that this effect doesn't need to stick in the long run.

I'll try testing in the original. Just need to find out why it's again slow under wine.

**Comment by lynxlynxlynx** [comment]
Param2 is indeed a fade speed. With 250, they practically pop in and out. So I'd map 0 to 1 round, 255 to instant. Also tested that there is no automatic reset; two effects are needed.

The opcode should also display a small white whirl (not the big one in the video — those are separate), but I couldn't identify it
