### ISSUE TITLE
[subviews] Dithering change during character animation

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1108]
#### Bug description
I suppose you can reproduce somewhere else but here (ar9101 [1017.470]) during character animation without moving he is partially dithered then not and so on.

subviews with SDL2+OGL

not tried with master.

#### Screenshots
![hidden_1](https://user-images.githubusercontent.com/55502325/102053058-6bc8e600-3de7-11eb-9ed7-a469f88252c6.png)
![hidden_2](https://user-images.githubusercontent.com/55502325/102053084-73888a80-3de7-11eb-9429-7ffea6a68bff.png)

**Comment by bradallred** [comment]
I'm having trouble reproducing this. Can you attach a save with an actor in a problematic position?

**Comment by FrElvire** [comment]
[000000049-bug.zip](https://github.com/gemrb/gemrb/files/5690484/000000049-bug.zip)

IMHO the problem is not really the animation, but the fact that character is not always dithered behind decors

**Comment by bradallred** [comment]
I dont see anything wrong

![iwd](https://user-images.githubusercontent.com/1126744/102115049-3a0c4b00-3df8-11eb-8f98-92456c7c7362.gif)

**Comment by bradallred** [comment]
what version of SDL 2 are you using? can you try building SDL from their repo?

**Comment by FrElvire** [comment]
ok, this is one more time the same problem : bad build option.... SDL2 but WITHOUT OpenGL :'(, sorry.

With openGL all is correct...

With only SDL2 I suspect theses sort of problem are expected, so can be closed ?

**Comment by bradallred** [comment]
hmmm, possibly? I'll have to look at it later.

**Comment by FrElvire** [comment]
used version : SDL2-2.0.12

**Comment by lynxlynxlynx** [comment]
Can confirm it still works fine for me on SDL1.

**Comment by lynxlynxlynx** [comment]
Trying the save with SDL2, I can reproduce both states. Some of the frames cause dithering, some don't:
![Peek 2021-04-29 13-20](https://user-images.githubusercontent.com/121515/116543176-d5a4e080-a8ed-11eb-81bf-8d3e0c83cf98.gif)
It looks like it's due to him interfering with the baseline of the other wall or not:
![image](https://user-images.githubusercontent.com/121515/116543281-f705cc80-a8ed-11eb-96a0-6e156ea238ad.png)
![image](https://user-images.githubusercontent.com/121515/116543315-0258f800-a8ee-11eb-90ee-6295e34eb293.png)

**Comment by bradallred** [comment]
I cant even load the save without a `nullptr` dref in `GameData::HasInfravision`

**Comment by bradallred** [comment]
but after working around it this is still just plain SDL 2 that has the problem SDL2+GL is still fine. SDL 2 can only blend one channel of the stencil.
