### ISSUE TITLE
[subviews] button from previous menu active if in current menu there's no button

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1118]
#### Bug description
button from previous menu active if in current menu there's no button

#### Steps to reproduce
1. Click on "cast a spell"
2.if there is no spell icon on the right, you can click as if you were in the previous menu

![previous_button](https://user-images.githubusercontent.com/55502325/103168446-9a0ce380-4833-11eb-8401-89bcf2df687d.png)

Another case:
1. Click on "cast a spell"
2.click on the right arrow to go to the next spell (if the number of spells is sufficient)
3.when there is no more right arrow, you can click as if it is still there

![speel_next](https://user-images.githubusercontent.com/55502325/103168468-c58fce00-4833-11eb-941b-9a3baa27a9d3.png)

**Comment by lynxlynxlynx** [comment]
Meh, this happens because view flags are partly responsible for button state as well now. So you think you're done by calling SetState(IE_GUI_BUTTON_DISABLED), but then a SetFlags can wipe it clean (when used with OP_SET). Reversing the order in Spellbook.py fixes this instance, but leaves the bigger fragile issue intact.

We have over a hundred OP_SET users in GUIScripts, so banning it is impractical. The cleanest thing I can think of is masking out Disabled in GemRB_View_SetFlags for buttons.

**Comment by bradallred** [comment]
setting the visibility flag instead would prevent interaction

**Comment by lynxlynxlynx** [comment]
Wouldn't that only work for cases where we want the control to be invisible as well?

**Comment by bradallred** [comment]
yeah, it looked like that was the case here from the screenshot. Doesn't matter tho, it also wouldn't matter much if doing `OP_SET` is happening somewhere.

**Comment by lynxlynxlynx** [comment]
Not very pretty, but it does the job:
http://sprunge.us/N52ojQ?diff

**Comment by bradallred** [comment]
maybe it would be more palatable to give `Button` an override for `FlagsChanged`? so if the state is disabled the disabled bit gets forced on there.

**Comment by lynxlynxlynx** [comment]
That was too zealous, so it broke other buttons, so I went with the original.
