### ISSUE TITLE
[feature] Favorite Spell - No Information || Time Spent with Party - Incorrect Value

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#117]
**Description**
Favorite Spell doesn't not get updated in the NPC record card - information is missing. Number of days and hours a NPC spent with party is incorrect. It displays the current in-game day and hour you playing. 

Time Spent with Party applies to all classes
Favorite Spell applies to all spell casting classes.

<details><summary>Screenshots</summary>

![no fav spell sorcerer](https://user-images.githubusercontent.com/17316115/53676478-c889f980-3c70-11e9-8413-9349ac554afe.jpg)

![no fav spell cleric](https://user-images.githubusercontent.com/17316115/53676479-c889f980-3c70-11e9-9f3c-f6291a25ee41.jpg)

![no fave spell bard](https://user-images.githubusercontent.com/17316115/53676480-c889f980-3c70-11e9-855d-ec31dddfbfb9.jpg)

![no fav spell bard](https://user-images.githubusercontent.com/17316115/53676481-c889f980-3c70-11e9-9703-69e7ecb83606.jpg)

![no fav spell fightercleric](https://user-images.githubusercontent.com/17316115/53676482-c889f980-3c70-11e9-9f1d-4e9016acf102.jpg)

![no fav spell thief mage](https://user-images.githubusercontent.com/17316115/53676483-c889f980-3c70-11e9-934b-a8d6f5ee91e9.jpg)

</details>

Sorry for dark looking screenshots I played with dimmed screen when making those pics.

**Comment by lynxlynxlynx** [comment]
It clearly does not display the current time, since it is not the same for your characters. It also takes into account any time you temporarily kicked them out. 

Spells don't care about class, but I did fix two little bugs now, which could have made the right favourite invisible sometimes. And added proper plurals to the rest of the games, if that was what was bothering you.
