### ISSUE TITLE
GUISTORE: add more input proxies for the scrollbars 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1260]
The item buttons don't allow mouse wheel scrolling yet, while the labels we can't do anything about.

**Comment by bradallred** [comment]
the labels aren't the problem, we do this on other windows (eg GUILOAD) by setting the scrollbar as the proxy for the window itself. The problem is that we have 2 scrollbars. I'm not sure of the best way to approach this yet.

**Comment by lynxlynxlynx** [comment]
Wouldn't setting the buttons individually (instead of the whole window) slightly improve the situation? From a user POW, I'd expect whole input regions to be mapped to each scrollbar. In this case, half-half, everything that's has a lower x than the scrollbar's and isn't taken yet.

**Comment by bradallred** [comment]
No, if you set a proxy on the individual controls then all evens are proxied including the mouse buttons. we dont have granularity on which events we proxy.

rather than adding complexity by allowing proxies to only proxy certain event types, I think the best/easiest thing to do is to create 2 empty views that overlay the buttons/labels and place it behind them. all scroll wheel events should bubble up to it since they aren't handled by the buttons/labels and then we just proxy those to the scrollbars.

**Comment by bradallred** [comment]
I'm not sure if that got all the different windows

**Comment by lynxlynxlynx** [comment]
Nice!
