### ISSUE TITLE
Fog of war corner glitch

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#132]
Fully visible squares with one corner neighbour invisible need alpha of the adjacent corner to the invisible square tuned down (uh, I hope it is clear what to do, look for artefacts in the fog of war edge).

**Comment by MarcelHB** [comment]
Can you name the game or screenshot something? Because I just tried to check a bunch of games for this issue and had the following, weird observations:

* BG1/2: no FoW at all, no matter what, every map is always fully explored? I tried save games or new games.
* PST (with FullHD Widescreen): Same as above.
* IWD: Same as above, original has some general glichtes anyway, as it seems (Win 7), see screenshot attached.
* IWD2: Looks good!

![iwd_shadow](https://user-images.githubusercontent.com/238558/62827189-c8e8d200-bbca-11e9-816a-b3a4c6764b7c.jpg)

**Comment by lynxlynxlynx** [comment]
Make sure you don't have `FogOfWar=0` in your gemrb config. BG1 for example has both the fog and shroud of war (the translucent version for stuff out of visual range).

The original report is age old, I think from Avenger, and was just migrated from the wiki list. I remember once testing this and confirming, but that was also back then.

BG1 looks find upon recheck (in the ruins with Ulcaster, where the fog is really finegrained). Nothing really stands out in the druid grove of BG2 either. Sure, maybe it would look even better if the seldom rectangular borders would be more dithered, but the report was not about this.

If you can't find a problem either, let's just close it.

**Comment by MarcelHB** [comment]
Yes, thanks, `FogOfWar=0` copied in my different configs ...

So, everything looks good to me, no obvious glitches for 360° in any of the games.
