### ISSUE TITLE
 Can't enter save name after clicking elsewhere in box

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1323]
#### Bug description
 Can't enter save name after clicking elsewhere in box

tested with bg1 & iwd1

GemRB version: master

#### Steps to reproduce
1. load save
2. create a new save
3. instead of typing his name click elsewhere in the box
4. can't enter save name even when clicking on save name field

**Comment by lynxlynxlynx** [comment]
It looks like it's from TextEdit's consistent disabling of its text container view. Not sure why we do that though.

**Comment by bradallred** [comment]
I assume you are inquiring about the setting of `IgnoreEvents` this was done to force events to be filtered though the `TextEdit` so we could obey the alpha/numeric/length filtering. Of course that predates the addition of the event proxy so we have a much cleaner method now. The filtering was broken anyway since the addition of `TextEvent`s since now thats how all text comes in and those bypassed the filters that were setup in `TextEdit::OnKeyPress`
