### ISSUE TITLE
PST: hive thugs are present when loading in GemRB, but not in vanilla 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1369]
#### Bug description
(from https://github.com/gemrb/gemrb/issues/1330) Extra two thugs appear when loading the save in GemRB. They aren't there in original. (Full story: there was a group of 3 thugs on the left, they were killed, and the save was made right after that.)

[save.zip](https://github.com/gemrb/gemrb/files/6863462/save.zip)
[gemrb.log](https://github.com/gemrb/gemrb/files/6863507/gemrb.log)

#### Steps to reproduce
Load game

#### Expected behavior
No thugs on screen

#### Screenshots
![Captura de pantalla de 2021-07-22 22-30-08](https://user-images.githubusercontent.com/1279852/126666579-bf223f0a-43f4-4751-83a1-d2e6885aef8f.png)

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by fizzet** [comment]
The same problem exists in other games that use ini spawns. Their spawn status is not preserved across reloads, so they fire again on load.

**Comment by lynxlynxlynx** [comment]
This should be easy to fix. Either the enter spawn shouldn't be executed on load, since the area was already inited the last time, or the create_qty and spec_qty key handling logic needs improving. It should be trivial to demonstrate if the former is the problem: in an area without spawning limits repeated loading and saving should quickly multiply the amount of actors.

**Comment by lynxlynxlynx** [comment]
Did a quick test in the mortuary and it works fine there:
- initial count of actors is 21
- save & load: 21
- kill 3 zombies: 18
- save & load: 18

It takes some care when testing, since 3 of them are actually in the ARE file. Once I got one of them to repeat the dying animation, but just one, just once. Time to check how ar0200 is different.

**Comment by lynxlynxlynx** [comment]
It's these two:

```ini
[new2_thug2]
spec              = [0.0.0.0.0.0.125]
spec_var          = GLOBAL::Respawn_0200
cre_file          = thugb1d
ai_specifics      = 125
script_Default    = 0200thg1
spawn_point       = [1049.1016:0]

[new2_thug3]
spec              = [0.0.0.0.0.0.126]
spec_var          = GLOBAL::Respawn_0200
cre_file          = thugb1e
ai_specifics      = 126
script_Default    = 0200thg1
spawn_point       = [982.1029:0]
```
= no ignore_can_see?? That's already suspicious.
