### ISSUE TITLE
BG1/BG2: Return to main weapon/ability bar by clicking on portrait/empty space or pressing escape

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1421]
#### Description
I'm not sure whether to call this a bug report or feature request.
When you click on anything on a characters toolbar that opens a second selection, like spells, abilities, bags, clicking on a) the empty space on the bottom toolbar and b) on the characters portrait and c) pressing escape should return to the main bar. 

With GemRB, clicking on the empty space does nothing. 
- Except on the bag "use item" submenu, clicking on the empty space returns me to the main bar, but the cursor changes to the "cast spell" cursor and uh... most of the time nothing happened, but once I cast power word: Kill :D
- This doesn't happen in 0.8.8, the item bar doesn't close either. 

Nothing happens when clicking on the portrait if that character was already selected, I have to select a different character and then go back. 
This also didn't work on 0.8.8.

Pressing escape also doesn't work to bring back the main bar. 
The escape button used to work in 0.8.8, has been broken since 0.9.0.

#### Additional context
Words are bad, here is a vid (original game)
https://www.youtube.com/watch?v=aluj6D6qTtQ

Here is the GemRB behaviour
https://www.youtube.com/watch?v=MuDjMIoLP7o
(that spell thing is kinda weird)

**Comment by lynxlynxlynx** [comment]
It's related to a change that made us not cancel things on right click. Adding it all together can make for a bit annoying use, I agree.

The first video is marked as private.

Basically the action window should reset itself if clicked.

**Comment by Laulajatar** [comment]
Oops, fixed the vid.

**Comment by bradallred** [comment]
`GameControl` already listens to all esc presses and calls `core->SetEventFlag(EF_ACTION|EF_RESETTARGET);` _unless_ the window is disabled or the `IgnoreEvents` flag is set, which I suppose _could_ be the case if we present that action sub window as a modal. The fix for that could be as easy as removing the modal flag.

FWIW you can also add an event tap for right click to do the same 🤷 

https://github.com/gemrb/gemrb/blob/3bd81bd8ee16d35363daeb3367a9b763ffb3dd07/gemrb/core/GUI/GameControl.cpp#L663-L684

**Comment by lynxlynxlynx** [comment]
Do events on windows bubble up to gamecontrol if not handled? I thought it was separate.

**Comment by bradallred** [comment]
`GameControl` just installs some global taps so it can do certain things like the example above with tab/esc (or panning the viewport when the mouse is at the screen edge). Most events are handled in the normal way you would expect.

`WindowManager::NextEventWindow` _does_ return `gameWin` if there is nothing else, but isn't affected by the other windows handling the event or not.

taps don't handle the events either, they just let you spy. I _thought_ they would let you spy on all events, but the code appears to only invoke them if the event is otherwise unhandled. there probably isnt a reason we couldn't change it tho.

**Comment by lynxlynxlynx** [comment]
Escape was triggering the update, but was missing a var reset. I've added the resetting to Window itself for the rest.
