### ISSUE TITLE
BG1: Three white dashes on every character portrait

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1471]
#### Bug description
In BG1, every party member portrait on the sidebar has 3 white dots. 

#### Screenshots
![unknown](https://user-images.githubusercontent.com/68446748/131211362-12dfaa73-2967-40af-b8e7-6ed559a6f932.png)

Looks like it could be the same white dash used in the character record sheet between icon and name of an effect: 
![unknown-1](https://user-images.githubusercontent.com/68446748/131211402-8248d49f-0a80-4998-a5ed-8611ebedd629.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by TimHyers** [comment]
I noticed that when I was working on issue #1462 that when the portrait refreshes after leveling up the white dashes appear.
![DashesLvlUp](https://user-images.githubusercontent.com/45843778/132876527-ce0f0753-c690-459a-9ddd-6b307a3a754f.PNG)
(The '+' presumably covering up the third dash)

But after completing the level up the dashes are gone
![DashesGone](https://user-images.githubusercontent.com/45843778/132876729-2e21ea27-e9b6-47db-9481-5938cf7f7acb.PNG)

I'm not sure how helpful this is, but it might be good to look at. Do you know how to get the dashes to persist?

**Comment by bradallred** [comment]
the problem is here
https://github.com/gemrb/gemrb/blob/6eee2c991afcef9a4d2a2001f6f1d650870a8760/gemrb/GUIScripts/GUICommonWindows.py#L1738-L1741

`bytearray([32])` is probably the '-' character in this font. the original code used a space character (ascii 32). it looks like the "space" character for this font is actually `bytearray([238])`

**Comment by MarcelHB** [comment]
What I just noticed in addition, and since it's visible on the very first image of this report: the green frame at the bottom indicates some kind of non-rectangularity, like the right border is one px shorter than the left one.

**Comment by lynxlynxlynx** [comment]
The zigzag was there before, maybe even before subviews, on SDL2 — I remember discussing it at some point.

This bug is fallout from changing the numbering from frames to cycles, +1. Blank is 33 in bg1, when you count from 1 (cycle 32). But it's also more narrow, so spacing is not ok. IWDs have a fullwidth space at frame 64, but no cycle with it, so no luck with this approach.

We could go back to generating our own spacer glyph or adding more labels, but since only bg2 has other icons in the top row, not spacing the icons out and right aligning should work. There's only the levelup plus anyway.

Btw, frame indices are nicely visible here:
https://github.com/gemrb/gemrb.github.io/blob/master/assets/img/states-overview.png

**Comment by bradallred** [comment]
the "zigzag" is a well known [SDL bug](https://github.com/libsdl-org/SDL/issues/4001). Try upgrading your libSDL.
