### ISSUE TITLE
Please make a launcher with some pathfinding algorithms like other multigames engines (scummvm,residualvm,etc)

### ISSUE THREAD

**Issue by Askmewho** [gemrb/gemrb#150]
**Description**

Its a PAIN IN THE ASS trying to make any of the games run, even with the extensive documentation, seems to me extremely unfriendly to setup 

**Additional context**
I wanted to kill my self after finished this engine gameplay tests. btw, it runs great.
thanks to the effort!!!

**Comment by lynxlynxlynx** [comment]
What was the problem? You only have to set the game path and point gemrb to the config that you edited.

Or how could it be done better? Don't know what you mean with this "pathfinding".

**Comment by Askmewho** [comment]
Because the games differs on folder location of the files depending of the game version.. It just needs to be an easy launcher , choose the path location, search than everything its right and that is... And it was not the case, ive tried 2 different version of planescape and spent all the night to run it... Its not easy at all, not easy as just place a path on a .cfg file, it needs files from other locations, and it wasnt easy at all. Just as a recommendation. Best wishes, closing.

**Comment by lynxlynxlynx** [comment]
The game version shouldn't matter, we even added extra search paths to make the CD paths redundant for most cases (eg. some games have a data/Data folder).

I've also made a video:
https://www.youtube.com/watch?v=32BZouraDPM
The cache problem has had a workaround since and the game type is set to auto, so only the main path needs to be set (at most one extra). Which versions of pst do you have?
