### ISSUE TITLE
IWD2: Encoding misinterpretations in message window

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1515]
Happy about seeing #1499 fixed, I gave it a try with German. While the exceptions with Py3 are gone indeed, I noticed something new:

In IWD2, the message box takes the string from the loading screen. Instead of displaying any umlaut, it prints other chars that reside on the respective bytes in ISO-8859-1 (that's the TLKEncoding):

![Screenshot_2022-01-12_23-57-30](https://user-images.githubusercontent.com/238558/149238086-eca55f94-e5e9-4e01-a313-021b6eb9e375.png)

Other things work well (see the `ß` in the line above).

**Comment by fizzet** [comment]
Sigh. At this point, keeping Python 2 compatibility is becoming a real drag. Is there a good reason not to toss it?

**Comment by lynxlynxlynx** [comment]
I don't remember discussing it, but it was an option already when doing the port  #101. Then that turned out to be relatively easy and it was all done just before the planned big releases, so we both didn't have much feedback yet nor pondered much about its future. So yeah, it's a good time to do it now.

I don't think it would hurt our portability, so I support sunsetting it.
