### ISSUE TITLE
remove PyStringWrapper

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1524]
Continuation from #1517 #1516

**Comment by bradallred** [comment]
so we cant rid ourselves of `PyStringWrapper` because we need something to hold the decoded string data if we need to convert a python string to `String` (or whatever).

I have removed the old `PyString_AsString` compatibility function as all uses of it have been updated to other APIs
`PyStringWrapper` also no longer implicitly converts to `const char*`, so that fixes the pitfall we wanted to avoid originally.
