### ISSUE TITLE
%ls formatting needs to be rewritten with libfmt

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1527]
this is needed to make more progress on #1516

since `String` will be UTF-16 we need to use the `WideToChar` formatter so we can convert to whatever system encoding the logging system uses.

we should probably also take this opportunity to remove `print`.

effectively this means that the logging system needs to be refactored to use libfmt

**Comment by lynxlynxlynx** [comment]
I can look at this if you want. It'd be good if you addressed the drawing regressions in the meantime, since that's completely your area & design.

**Comment by bradallred** [comment]
thanks, I've assigned this to you. I am aware of the drawing issues, but it's not a simple fix and will require some of the [roadmap](https://github.com/gemrb/gemrb/wiki/Graphic-Rendering-Roadmap) to be implemented.

**Comment by lynxlynxlynx** [comment]
We've accrued quite some good work, so I'd like to make a new release within the next few months. Meaning we should try not to get into anything too invasive on master.

**Comment by lynxlynxlynx** [comment]
I'll go function by function, leaving some scaffolding (back to char) until all are converted, so the work can be split and easier to look at. I've started with `error`, since it has fewer users and is a bit easier to regex into submission. 

Checking what would happen in variadic function form: we'd create 20 instances, which sounds like a lot, but I don't know if va_list is eventually any better. Also the linker doesn't like it in variadic function form, as if the GEM_EXPORT attribute wasn't passed along. Any preferences?

**Comment by bradallred** [comment]
I’m not near a computer to find the docs, but libfmt has an “arg list” type you can use to pack all the arguments then pass it to format. We don’t explicitly need to go the variadic argument route.

**Comment by lynxlynxlynx** [comment]
Turns out it's practically unavoidable, as fmt needs type info at compile time.
WideToChar can become quite noisy — I guess we can't add a formatter directly to String easily?

Here's error for any comments:
http://sprunge.us/VMxbVC?diff

**Comment by bradallred** [comment]
> WideToChar can become quite noisy — I guess we can't add a formatter directly to String easily?

I'm not sure what you mean by noisy.

A formatter directly to `String` should be nice, but I couldn't figure out a way to do it since libfmt provides its own formatter for `std::wstring` and `std::u16string` both and I dont know how to make the compiler select our version.
