### ISSUE TITLE
Do something with "NoteString"

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1537]
the language ini files have a `NoteString` value, but we don't use it. There is commented out code:

`//TextArea::SetNoteString( ini->GetKeyAsString( "strings", "NoteString", NULL ) );`

but there is no `TextArea::SetNoteString` and I've no idea what it was ever for.

**Comment by lynxlynxlynx** [comment]
> externalized the 'NOTE:' string that is used in highlights in PST TextArea
A hardcoded prefix.

**Comment by bradallred** [comment]
is there a strref in the TLK for that? Or is it hardcoded like
https://github.com/gemrb/gemrb/blob/c086f1e3af2377bf225d60115611dcda17045ee2/gemrb/core/GUI/Button.cpp#L419-L430

**Comment by lynxlynxlynx** [comment]
There isn't, that's why it was added. 85 strrefs have it and it was actually added for coloring that text, not adding it now that I found the original code: 1ed73321

**Comment by bradallred** [comment]
im guessing that doesn't work anymore :)

We probably have a better means to that end now. `TextArea::AppendText` already handles the drop caps which use `COLOR_INITIALS`. Set that to white and change the code to conditionally work for the first word instead of the first letter.

That does nothing for the localization, however. If I understand correctly, we could add custom `ieStrRef` definitions above 450000 and move `OVERRIDE_START` past them. then the language ini file can specify a map to define those strrefs with a localized value.

**Comment by lynxlynxlynx** [comment]
You ripped it out when doing subviews, so no. It's all so ugly because this is in the middle of a string, not at the start, so you don't know what to search for if it is not explicitly mapped out. The caps approach may work and could be done on the python side, but the data needs to be exposed to it then.

As for the /key/ strings, are you sure they were localized? @MarcelHB?

**Comment by bradallred** [comment]
the strings I was referring to were the hardcoded strings we use various places such as tooltips, but certainly we could handle any string we want to localize the same way.

if `NOTE:` isn't localized, then we could also handle it as a special token and use `STRING_FLAGS::RESOLVE_TAGS` to rewrite it with markup. We could even rewrite it with a localized string.

**Comment by lynxlynxlynx** [comment]
I don't see a point in adding another translation layer, since that's exactly the role of the TLK. And I would also argue that the four tooltip strings that are our own addition don't warrant translation at all. We could even remove them, but I don't feel strongly about that.

How would we parse XXXX: as a token, when it isn't wrapped in <>? Best not to pollute the core with hacks for this hack and do it in the inventory display function.

**Comment by bradallred** [comment]
I didn't suggest a new layer, using the TLK was exactly my suggestion. The tooltip strings are useful as they tell you what hotkey is mapped. I assumed we have other hardcoded or non-TLK strings that could be localized.

I agree on keeping hacks out of core. Often I just like to spitball all possible solutions to a problem. I've been around long enough to realize sometimes it leads to more optimal and non obvious solutions. in actual workplaces its important to document rejected approaches as much as it is to document the one taken.

**Comment by lynxlynxlynx** [comment]
Maybe not a new layer, but definitely new complexity, not the usual way TLKs are used. We shouldn't be hardcoding text in the first place though, even strrefs we try not to*. So if you know of any other hardcoded strings, let's look at those first and understand the situation better.

*But we are sometimes lazy, eg. the hidden iwd2 roll stuff that's now in ieStrRef is pointless to move to strings.2da, since no one else can benefit from it.

**Comment by bradallred** [comment]
I agree, we should information gather more first.

**Comment by MarcelHB** [comment]
I just did a quick test on some of the games, and you cannot specify any localiazable keys, i. e. "Page Down" cannot be used. Not counting any INI settings, we can guess so that they are not.

**Comment by lynxlynxlynx** [comment]
Re Variables: you mean tokens? They're not unique, we don't and can't have a mapping to strrefs, so I don't see how you could cleanly replace them. Or why, GetString is already the same API.

**Comment by bradallred** [comment]
I was mistaken in my recollection of the commented out code for previously dealing with "NoteString" thinking it was setting a variable to lookup when using the string. Its not, but we also don't need specialized APIs for every string so `TextArea::SetNoteString` wasn't a good solution either.

I'm saying that that resolving strings from within code should go though `GetString` using an `ieStrRef`. The implementation being whatever makes sense (use underlying TLK override, some 2da, ini, combo, whatever), but obviously the strrefs need to be in some unused range that we reserve.

**Comment by lynxlynxlynx** [comment]
Well, so far there has been no need for the complication, so I wouldn't bother forcing NoteString into an artificial strref, since text editing can be done completely on the python side. We'd use GetString on the actual strref and then edit the resolved text, adding the color tags as before. To fetch the string from core we either store it in a variable (token, since vars don't take text) or add another possible value to GemRB.GetSystemVariable. No need to touch the text subsystem at all.

**Comment by bradallred** [comment]
right, its clear I've confused the conversation by talking about something other than NoteString. I completely understand that NoteString isn't a hard coded string (its part of a series of other strings) and the appropriate way to deal with that is via Python text chunking and markup, since apparently this text isn't at the beginning of a string (otherwise we would just let `TextArea` do its thing with `COLOR_INITIALS`).

The side conversation about hardcoded strings is completely unrelated to NoteString and that is where I am saying _if_ we deem localization necessary for them, then using the existing API (`core->GetString()`) for resolving them is preferred. Clear now?

> To fetch the string from core we either store it in a variable (token, since vars don't take text) or add another possible value to GemRB.GetSystemVariable.

this I don't follow. I thought the strings in question were from the TLK, which means just call `GemRB.GetString` then manipulate it in Python before sending it to `TextArea`. I don't understand why we would need anything additional.

**Comment by lynxlynxlynx** [comment]
We don't know what to look for in the string without the data that's in the ini. But I got an idea when I went to sleep — I'll check if we can just wing it with a strict enough regex... `^[[:upper:]][[:upper:]][[:upper:]][[:upper:]][: ]..[[:lower:]"]` works perfectly in English, without false positives. I suspect POZN is missing the colon, but it should work fine as well.

Hah, it looks like they even documented it:
> @49156 = ~Testocles glares at you.
> 
> NOTE: This is a narrative text test.  Will it work?  Will it be displayed in a different color than the dialog text?  It would sure make me happy.
> 
> Testocles is now back to speaking normally.  That's a relief.  That narative text was just *too* intense.  Uh-oh,.... here we go again...
> 
> NOTE: Narrative text color is activated by "NOTE:" on the beginning of a line.  It will end after 2 consecutive <CR> characters.  For instance, the word Salad should still be concidered as part of the narrative text, even though it is a new line.
> SALAD - See?  Make sure narative text ends with 2 <CR>'s so this doesn't happen.
> 
> Would you like to go back to the main menu?~

I really need to get my pst back in order — I couldn't find any screenshots. One instance is visible with the zombie key in the first room already.

**Comment by Mingun** [comment]
Localized Russian version of PST from http://pst-l10n.wikidot.com have localized `NOTE:` text and it is colored as in original.
![torment_F12As9kchc](https://user-images.githubusercontent.com/450131/152546960-058558ae-a928-4253-b3b8-7e514162fc7e.png)

I myself was surprised at this, because the Фаргус "pirate" translation of this text was in usual color, and in TLK I did not see any special markup.

They definitely patch the original exe in order to make this work.

**Comment by bradallred** [comment]
Markup is a GemRB thing. The originals use the "initial" font and color to do this. How they decide to apply it was the mystery.

**Comment by lynxlynxlynx** [comment]
I doubt that was the case here, but it would be easy to test.
