### ISSUE TITLE
Area animation ordering problems

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1563]
The iwd2 ar5300 area is full of fail:
![image](https://user-images.githubusercontent.com/121515/154561763-4f2db9c9-73d9-4327-bd62-24255c3368a8.png)

original:
![image](https://lparchive.org/Icewind-Dale-2/Update%2028/12-7.jpg)

So:
- [ ] all have wrong ordering,
- [x] the purple pillar thing looks as if squashed
- [ ] the bottom right lamp is ocluded by the wall behind it

Feels like iwd2 might treat a flag bit or two differently, but I haven't checked the data yet.

![image](https://user-images.githubusercontent.com/121515/154562264-8f0e7f1d-b57b-4947-894c-f7c0aeca2426.png)

**Comment by bradallred** [comment]
its because, for some reason, we set `GF_IMPLICIT_AREAANIM_BACKGROUND` for IWD2. try removing that.

**Comment by bradallred** [comment]
worth checking out bcd68dd to see if its related. I remember the original reason for that flag was IWD AR9101, but I noted in 1957b1a that the area works fine now without the flag since the subviews stencil changes.

maybe we still need it, but it seems like all we need it for is to order actors in front rather than also implying `A_ANI_NO_WALL`

**Comment by bradallred** [comment]
looks like I reintroduced that implication in e51cdb7 for #1202

hopefully there is a clean way to reconcile everything :)

**Comment by lynxlynxlynx** [comment]
Just for reference here's the whole evolution:
e32189c3b
29141def
1957b1a4
bcd68dd1

e51cdb70

`git log -p -Ssomekeyword` is very useful in such cases. But I remembered I need to ask something related about bg2.

**Comment by bradallred** [comment]
sure, but I dont know why it was kept. I dont know if it was important or if I just did it because i didn't want to risk breaking something.

**Comment by lynxlynxlynx** [comment]
Still in the data part:
In this area none of the heights are negative, NI can animate it just fine and I don't see any hacks in its code. So we probably don't need the GF. Toggling it off doesn't have a visible effect though.

Pink stuff: the area has 4 separate animations indeed and they're visible in gemrb somewhat — in the screenshot they all have tiny bounding boxes and are all bunched up above the lowest. All have the same z/height and location, but different bams with offset centers. It's as if we treated them as blocking actors, but that doesn't explain the tiny bboxes.

**Comment by bradallred** [comment]
> Toggling it off doesn't have a visible effect though.

toggling what off? do you mean `GF_IMPLICIT_AREAANIM_BACKGROUND`? looks to me like we want that here. the reason these are drawn beneath walls is that we aren't applying `A_ANI_NO_WALL` because those animations dont have negative height, so `GF_IMPLICIT_AREAANIM_BACKGROUND` has no effect. so remove the `anim.height <= 0` and it should work (tho dont know what else it breaks)

**Comment by lynxlynxlynx** [comment]
Ehhh, looks like it works fine in a fresh area, so the ARE in the save is just corrupted and the pinkies are fine.

**Comment by bradallred** [comment]
> Except perhaps needing to be blended more transparently

probably #1291

**Comment by bradallred** [comment]
I assume the lighthouse and inn mentioned in the previous issues still work?

**Comment by lynxlynxlynx** [comment]
yep
