### ISSUE TITLE
Bad formatting as of 79bdd2

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1621]
The syntax for cutting up strings is correct, but it looks like FixedSizeString doesn't get to use the fmt formatter in Format.h. So reversions like this are needed for most of the commit:

```diff
diff --git a/gemrb/core/GameScript/GSUtils.cpp b/gemrb/core/GameScript/GSUtils.cpp
index d73fe8c32..737c088fd 100644
--- a/gemrb/core/GameScript/GSUtils.cpp
+++ b/gemrb/core/GameScript/GSUtils.cpp
@@ -2243,7 +2243,7 @@ ieDword CheckVariable(const Scriptable *Sender, const StringParam& VarName, VarC
                if (*varName == ':') {
                        varName++;
                }
-               context.Format("{:.6}", VarName);
+               context.Format("{:.6}", VarName.CString());
                key = Variables::key_t(varName);
        }
        
```
Could be easily done or swapped for SubStr, but I think it's better to add or fix the formatter, so we don't need to manually extract the string.

**Comment by bradallred** [comment]
I think if that were the case we'd be seeing a compile error.

It seems like the custom Formatter isn't obeying the specifications following the ':', the string is copied in entirety. It's possible we need to override the `parse` method to handle this ourselves, but we are inheriting from `formatter<const char*, char>` so I would have thought that should handle everything.

obviously we need to fix this, but `SubStr` probably should be used in most of these cases since its much faster and more clear: `context = SubStr(VarName, 0, 6)`
