### ISSUE TITLE
[IWD2] Paperdoll doesn't update appearance when changing colors

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1690]
I'm not sure if this ever worked, or how it works in the originals, but I expect that _something_ is supposed to change appearance wise.

This affects both chargen and the inventory.

#### Screenshots
<img width="335" alt="image" src="https://user-images.githubusercontent.com/1126744/187056990-ae83383a-c7fd-4b09-aae8-3a1017f16bd6.png">

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
iwd2 is different from the rest in that we draw an actual animated avatar, not the paperdoll. The original didn't use paperdolls either, but what looks like SSW facing avatars in the standing or ready stance. We use walking, but that's trivial to change, since we just append the iwd walking stance suffix ...
