### ISSUE TITLE
Pretty fog of war

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1760]
#### Bug description
Original BG2 makes fog soft when 3D acceleration is enabled. Without 3D, it's ugly and jagged, just like current GemRB one.
Not a big issue per se, but it does stand out for someone used to the original.

#### Steps to reproduce
Just look at fog.

#### Expected behavior
Pretty fog.

#### Screenshots
![Captura desde 2022-12-06 07-14-10](https://user-images.githubusercontent.com/1279852/205775092-38aeb8c2-bfb9-4f9c-8e22-f29474d3f935.png)
![Captura desde 2022-12-06 07-05-09](https://user-images.githubusercontent.com/1279852/205775174-80c6fbe0-28a6-4d65-8293-0534be8da530.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
are there just a different set of sprites? or is it applying an effect?

**Comment by bradallred** [comment]
yeah, but that could also just be a 32bit sprite with a proper alpha channel. The "ugly" sprites are just color keyed so have either complete opacity, or transparency with no in between.

**Comment by bradallred** [comment]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/1126744/206484767-0c6ebeb7-2b3d-411e-9a64-763731c28f87.png">

It looks like it's probably 32bit sprites judging from the settings options. Just gotta locate them and choose them. I wonder what other sprites are supposed to be 32bit.

**Comment by MarcelHB** [comment]
I can see smooth fog with 3D Acceleration enabled, regardless of that texture setting. I personally never did because these games always had other glitches for me then.

Not sure if any of my Win tools support APIs that old but I can later try to find out what BG2 was trying to do in this case.

**Comment by bradallred** [comment]
If there isn't a sprite, then I would suppose a simple Gaussian blur. Looking at the glsl from the EE editions shows they indeed are using a blur for something.

**Comment by MarcelHB** [comment]
It's actually quite simple: For a full cover, a quad primitive with some dark greay and alpha = 0.5 is blended over the background:

![trace_full_cover](https://user-images.githubusercontent.com/238558/211888230-96d96b96-c871-4dfa-913c-0ef444fb9a3b.png)

For some fog edge, they draw a triangle fan and make some corners alpha = 0 so that OpenGL interpolates the transparency to where needed:

![trace_semi_cover](https://user-images.githubusercontent.com/238558/211888408-85c41d43-921e-4c00-a17b-150d6d59e9d6.png)

**Comment by bradallred** [comment]
We can probably do something similar with `SDL_RenderGeometryRaw`, but that requires SDL 2.0.18 or newer

**Comment by MarcelHB** [comment]
Aside from a version check, we'd also need a better place than `Map` for hiding SDL details, but also not `SDL20Video` for having some specific application logic, don't we?

**Comment by bradallred** [comment]
well yeah, we'd want to add a DrawGeometry interface in Video and just implement it.

I'm also not if the SDL software renderer behavior would be the same as OpenGL, but I wouldn't worry about that. either it works or it doesn't. Thats why there is a setting.

**Comment by MarcelHB** [comment]
Does it make sense to have something like `video->CanDrawGeometry()`? Since it's drawing of goodies only for what we know, and the fallback here is using `FOGOWAR.bam`, then there is probably no reason to be concerned about old versions, or software rendering in case it's bad or insufficient.

**Comment by bradallred** [comment]
I'd just leave it unimplemented on backends that don't have the capability. the default setting would be to use `FOGOWAR.bam`. 

SDL 1.2 is going away soon, so with only the SDL 2 driver, I'm not sure there is a way to test `SDL_Renderer` to see if it supports `SDL_RenderGeometryRaw` (other than an ifdef for SDL version). I would assume since there is an implementation for software all the typical (metal, OpenGL, DX) all support it too, but I haven't checked.

You're right tho, my current plans for an SDL2 software renderer wouldn't use `SDL_Renderer`, so it wouldn't have this capability without either:

1. somehow mixing `SDL_Renderer` with `SDL_GetWindowSurface` and `SDL_UpdateWindowSurface`. The docs say you cannot mix with the rendering API, but perhaps if forcing the software renderer it would work ok.
2. stealing the SDL software 'SDL_RenderGeometryRaw'  implementation
3. obtaining the address of the underlying function that doesn't take `SDL_Renderer` and just calling that (if one exists)

Also, let's try to keep our `Video` API as simple as possible. We probably dont need all the parameters provided by `SDL_RenderGeometryRaw`.

**Comment by burner1024** [comment]
Awesome!
