### ISSUE TITLE
VFS: get rid of most fixed filename buffers 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1847]
Both Sonar and now also Coverity keep warning about the dangers of potential overflows and while our _MAX_PATH is big enough for practical purposes, all the C char buffers now stand out even more. And it's not really friendly to non-ascii encodings anyway.

Some things may be better as-is due to the host APIs we plug into (unchecked), but at least all the path manipulation can be converted to String and that would remove most users of _MAX_PATH already. 

IIRC @bradallred also mentioned something to this effect somewhere, but it's good to have it tracked either way.

**Comment by bradallred** [comment]
> path manipulation can be converted to String

Ultimately, the APIs for the filesystem operate on `char` buffers that are expected to be encoded in a particular encoding, which depends on OS. We can ofc use `std::string` instead of `char[_MAX_PATH]`. This is for *nix, no idea about other systems, so we might need a `Path` typedef to use the appropriate buffer for other platforms.

Nowadays, `std::filesystem::path` is the ideal way to do this in a cross platform way that handles the encoding and conversion between char widths internally. That isn't available until c++17, however.

Generally, only things that are displayed in the GUI need to be `String` (`wchar_t`), which will eventually mean a subset of UTF-16 (#1516). We've been steering everything else towards UTF-8 for simplicity and its general compatibility with things like ASCII.

**Comment by MarcelHB** [comment]
For Windows (at least Win API) we need wide chars but that max-length test can be rewired. I can look at this for having both platforms.

**Comment by bradallred** [comment]
ok PR #1857 should resolve this, with possibly the exception of Windows code I cannot fix.

**Comment by bradallred** [comment]
@MarcelHB what needs to be done for Windows? That appears to be the only place left where we are using fixed size buffers. We can open a new issue for it if its not something we can quickly address.

**Comment by MarcelHB** [comment]
I'll have a look at it. Just need to find the exact Sonar complaints.

**Comment by bradallred** [comment]
im not sure they would complain about windows code. The offenders are in PluginLoader.cpp and VFS.cpp. I'm not sure they all need to change, but VFS might have a better way of working. Its also totally fine to say "goo enough" and close this :)

**Comment by lynxlynxlynx** [comment]
Just git grep for _MAX_PATH; the only other user is in Vita-specific code. Sonar just complains that fixed-size buffers are prone to overruns and bugs/exploits like that.
