### ISSUE TITLE
Bump fmt 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1864]
There have been new releases and hopefully the last also fixes the flood of gcc13 warnings. We're currently on 8.1.1.
https://github.com/fmtlib/fmt/releases

**Comment by lynxlynxlynx** [comment]
A wink from the PR department: https://github.com/fmtlib/fmt/issues/2912 ;)

**Comment by bradallred** [comment]
apparently I should have done this as a PR... trying to deduce why gcc is complaining

**Comment by lynxlynxlynx** [comment]
Besides getting it back to build, did you have any other plans with the update or can we close this?

**Comment by bradallred** [comment]
I'll go through my notes and add anything. We already have a in issue for unicode conversions (#1516) and I can explore using fmt for conversions there.

I may have to revert the update, since im struggling to figure out why GCC is considering our `format_as` template for types that clearly aren't enums. I'm very puzzled.

**Comment by lynxlynxlynx** [comment]
dfaea688892 compiles for me on gcc 13. I checked and fmt still prides itself to work on even gcc 4, but perhaps 7 has something incompatible.

**Comment by bradallred** [comment]
yeah, its hard to see how this isn't a gcc/libstdc++ bug, but I've gone ahead and just dropped that template and used `fmt::underlying` instead.
