### ISSUE TITLE
GitHub: Make running of Sonar scan work/conditional

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1891]
#### Bug description

If a PR submitter does not have access to the required secrets, sonar test will run anyway, emit megabytes of whatever-it-is logs but will fail at the end (30min+) because of missing credentials.

Can we maybe cut this early to make it green? I found this approach: https://stackoverflow.com/questions/70249519/how-to-check-if-a-secret-variable-is-empty-in-if-conditional-github-actions

Otherwise, you can also even hard code who is allowed to request steps over if-checks on `GITHUB_ACTOR`.

**Comment by lynxlynxlynx** [comment]
I agree that the current situation is bad. The right fix is to make it work, since it's sort of a gatekeeping process, not to disable it.

Very recently they cracked automatic analysis, so we can just move over to using that and retire our custom workflow, which will also ensure PRs get analysed:
https://docs.sonarcloud.io/advanced-setup/automatic-analysis/

**Comment by lynxlynxlynx** [comment]
Ok, it works and is comparatively very fast. :)
