### ISSUE TITLE
 Problems in MSVC Debug build

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1937]
#### Bug description
BG1. In MSVC, in the Debug build, the interface buttons do not work, the Journal partially does not work, and the wrong save files are loaded. Everything works fine in Release. This creates problems when debugging.
The journal did not work also in 0.9.2.
In commit https://github.com/gemrb/gemrb/commit/2e78ef6c5576c58c3e3295ae7a2c655f07534054, the wrong save file began to load.
In commit https://github.com/gemrb/gemrb/commit/9f14c25007a01e743ad97f30056eb4fde5ca56c8, the interface buttons stopped working.

**Comment by lynxlynxlynx** [comment]
Typically it's the other way around and release builds don't work due to reliance on some side effects in asserts (that get optimized out). When you say the buttons don't work for you, what do you mean and which buttons?

**Comment by Dreamkins** [comment]
![Screenshot 2023-11-26 131432](https://github.com/gemrb/gemrb/assets/119408536/905c64d7-fe21-4257-81c1-12dde255b410)
![Screenshot 2023-11-26 131342](https://github.com/gemrb/gemrb/assets/119408536/7286bb11-fbac-4b24-a471-2ff28f00888c)
![Screenshot 2023-11-26 131309](https://github.com/gemrb/gemrb/assets/119408536/cd70b828-8509-4f53-864b-e9eb40407247)

**Comment by Dreamkins** [comment]
Wrong save loaded
![Uploading Screenshot 2023-11-26 131759.png…]()
![Uploading Screenshot 2023-11-26 131821.png…]()

**Comment by Dreamkins** [comment]
In my experience this may be due to an uninitialized variable. In the Release it is cleared to 0, and garbage remains in the Debug.

**Comment by Dreamkins** [comment]
It's very strange, but that's how it works
![Screenshot 2023-11-26 163217](https://github.com/gemrb/gemrb/assets/119408536/a6a5b74e-4e1c-4484-9678-fc2f44e4d2a6)
![Screenshot 2023-11-26 163313](https://github.com/gemrb/gemrb/assets/119408536/53cc836d-8477-4165-a6ef-a2a831946886)

**Comment by Dreamkins** [comment]
```
	operator StringView() const noexcept {
		return StringView(str, len);
	}
```
It looks like the object is deleted by the destructor before it can be returned.

**Comment by Dreamkins** [comment]
> what is the value of `core->config.SystemEncoding`? Can you try something like `UTF-8`?
windows-1251
How might this relate to the current problem?

**Comment by bradallred** [comment]
because we are constructing the wrapper like this: `PyStringWrapper(obj, core->config.SystemEncoding.c_str());`

and the implementation of `PyStringWrapper` used to use "strict" conversion errors so that could be a point of failure. I have changed this to not be strict, so it might work now, but potentially with some unicode code points in the text where the conversion fails. But this will show where that is happening so we might diagnose the underlying issue.

can you try again with the changes I've made?

**Comment by Dreamkins** [comment]
Yes, I'll try now

**Comment by Dreamkins** [comment]
Nothing has changed, everything is as in the screenshot above

**Comment by bradallred** [comment]
are there errors in the log after loading into a save?

> How could this help if I'm using the English version of the game?

Because you've stated that your encoding is set to `windows-1251`, which is unusual for English. you can try changing the encoding in your config to "UTF-8", which should work fine for English.

I also dont think that we should be using the system encoding for most of these `PyString_AsStringView` use cases. Most of them are for 2DA lookups, which should be done in UTF-8.

**Comment by bradallred** [comment]
> How could it even help that I save a temporary variable if the problem is in the encoding?

Because the `PyStringWrapper` returned from `PyString_AsStringView` goes out of scope at the end of the line and the `StringView` just points to data, it doesn't copy any. This _is_ something that we need to fix, as I mentioned in #1938. We just would prefer you to change it so that the temporary just gets passed into `GetKeyMap->LookupFunction` instead of adding temporaries and removing implicit conversions.

**Comment by Dreamkins** [comment]
I try
`config.SystemEncoding = "UTF-8";// iconvCode;`
But it didn't help

**Comment by bradallred** [comment]
ok, no matter. I needed to fix the other bug anyway. Just was wondering how your execution path differs since I wasn't seeing any ASAN complaints. It seems like I am on a code path that uses the underlying bytes of the PyObject and you are not. But the changes I just committed should make both paths work regardless.

**Comment by Dreamkins** [comment]
The buttons work! But the Journal is empty.

**Comment by bradallred** [comment]
Do you know why? Is it the `Color` issue from #1941?

It might be helpful for you to look into AddressSanitizer. Recent versions of MSVC do support it. It would reveal any areas where we are accessing memory beyond the lifetime of objects, if that is in fact the issue for the journal like for the others.

**Comment by Dreamkins** [comment]
No, thanks!
