### ISSUE TITLE
[subviews] message window text overwritten

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#196]
BG1. Load the mission pack save, get back control and dual class Abdel the protagonist. When you close GUIREC, the MessageWindow text will be garbled, like it was drawn on top of previous text. It restores proper operation as soon as something else is appended, though perhaps some content/history is lost.

Might be related to the fact that dualclassing will make some items unusable, so we try to dump them to the inventory, which is full, so we warn about it and dump on the ground. The warning is slated for the GUIINV mini-message label, so perhaps something is wrong with the exchange, since IIRC we now dump all that to the main message window too.

![image](https://user-images.githubusercontent.com/1126744/65365300-8d7ff100-dbd5-11e9-9228-9f3b78799371.png)

**Comment by bradallred** [comment]
I've noticed this when loading some saves in BG2 as well. Could be something along the lines of text getting appended while the dimensions are 0 causing the overlap. I'm not sure why changing the dimensions doesn't refresh things tho.

Frustratingly, it doesn't happen every time for me... maybe its all related to the load screen tip text. Might be it has its own newlines and we aren't properly taking that into account? Do you know if the text in your example has any newlines or other odd characters in it?

Its been so long since I've been in the code I don't know a good place to start looking other than maybe search for FIXMEs and TODOs in TextArea and TextContainer.

**Comment by lynxlynxlynx** [comment]
I don't have the right computer here, but I got at least three consecutive repetitions with the case above. I can try reproducing a couple more times and also checking with the equivalent of `MessageWindow.SetText("")`.

**Comment by bradallred** [comment]
I can reliably reproduce this by changing areas!

Additionally, it only does this the _first time_ you change areas. Even if you reload the game it continues to work correctly. You must exit the game for it to bug out again.

Seems then like this bug has something to do with an uninitialized value or something. I haven't had time to debug at all.

**Comment by lynxlynxlynx** [comment]
Running through valgrind show the problem occurs on first area entry or exit already, for my use case. Because everything is so slow, you can see it already in Sarevok's chamber, before being teleported out. It's just two lines, since it's not expanded yet, but "Paused for chapter text" was over it. I's displayed by textscreen, but it shouldn't matter. 

The valgrind log itself had nothing interesting. I guess it's time for manual intervention.

**Comment by bradallred** [comment]
I can no longer reproduce this by changing areas. I'm guessing the recent changes to the interface load order have "fixed" it. Do we have another reliable way to reproduce this using BG2, IWD2, or PST?

**Comment by bradallred** [comment]
I still haven't dug into this, but I have been able to verify its a repaint issue and not an actual bug with the layout overlapping.

**Comment by bradallred** [comment]
also, judging by the issue I witnessed in 54b64dc a good suspect would be `ScrollView::DidDraw`

**Comment by lynxlynxlynx** [comment]
Can confirm it works properly now.
