### ISSUE TITLE
Another UI performance drop

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2095]
#### Bug description
Feels somewhat similar to #2087. I'm here and there is nothing moving:

![cg_fps_drop](https://github.com/gemrb/gemrb/assets/238558/ab253eb0-6169-4346-8c87-8e059ce22c38)

Yet, the more text to the right, the bigger the FPS are going down. Also: scrollbar elements are missing despite being useful here. Not sure if related to this problem for now. Anyway, plenty of font rendering going on:
![tracy_font](https://github.com/gemrb/gemrb/assets/238558/e2e36e7d-6172-4435-9e9c-ade0dac21f30)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
That's interesting, the scrollbar actually works, we just don't display it. Maybe something goes wrong when we recreate it, since it's connected to the textarea.

I can imagine it being slow on load, since it has to layout to such short columns, but the actual rendering shouldn't be impacted by the invisible text — that sounds fishy.

**Comment by bradallred** [comment]
> Maybe something goes wrong when we recreate it, since it's connected to the textarea.

we dont relocate scrollbars. We ignore the ones in the CHU if they are assigned to a `TextArea` and the `ScrollView` creates its own. They are supposed to get hidden if there is no scrollable content.

The trace is impossible to decipher, but I don't think we optimize away printing text. `Font::Print` will [optimize away the sprite blitt](https://github.com/gemrb/gemrb/blob/a8b88eed79da48a14f5aace7a3216cbe14516439/gemrb/core/GUI/TextSystem/Font.cpp#L320), but I don't think anything stops the `View` from running the `Draw` code unless the entire `View` is clipped:

https://github.com/gemrb/gemrb/blob/a8b88eed79da48a14f5aace7a3216cbe14516439/gemrb/core/GUI/View.cpp#L252

**Comment by bradallred** [comment]
yeah, see this `TODO`: https://github.com/gemrb/gemrb/blob/a8b88eed79da48a14f5aace7a3216cbe14516439/gemrb/core/GUI/TextSystem/TextContainer.cpp#L370

**Comment by MarcelHB** [comment]
> The trace is impossible to decipher, but I don't think we optimize away printing text. `Font::Print` will [optimize away the sprite blitt](https://github.com/gemrb/gemrb/blob/a8b88eed79da48a14f5aace7a3216cbe14516439/gemrb/core/GUI/TextSystem/Font.cpp#L320), but I don't think anything stops the `View` from running the `Draw` code unless the entire `View` is clipped:

The trace just shows that the CPU is spending 95% of the drawing time of a frame in `Font::Print`.

Shouldn't we _just not_ be here at all? There is no content update here, so my guess is that we do not even go into `DrawSelf` (of a text container), but we do because maybe some dirty flag toggling is still too sensitive? Maybe like this FIXME in View.cpp. Just did not have the time to look deeper into this.

**Comment by bradallred** [comment]
> The trace just shows that the CPU is spending 95% of the drawing time of a frame in Font::Print.

Yes, but that's all it shows. I shows nothing about how you end up there. Lots of stuff prints. I don't doubt that it's the `TextContainer`, but it's always helpful to be sure.

> maybe some dirty flag toggling is still too sensitive?

You're using a tracing tool. Have it record calls to `View::MarkDirty` on the `TextContainer`.

I suspect the `ScrollBar` isn't really hidden, so maybe we have a separate bug there. I think in some cases we maybe we do use the `CHU` scrollbar because the background is baked in (possibly all of IWD2?). So we need to figure out what's going on there. You can use the `VIEWS` debug flag to get a visual of the hierarchy which could be useful.

The `FIXME` I mentioned in #2087 should still only impact frames that are changing, it's just an issue of drawing more than actually changed.

Sounds more like another invisible view that actually does have an area, but that should still show up with the debug flag enabled.

**Comment by MarcelHB** [comment]
Yep, it's a scroll bar with the invisible flag set but a non-zero area.

Will do more research later.

**Comment by MarcelHB** [comment]
Different example but I guess the same situation:

![iwd2_groups](https://github.com/gemrb/gemrb/assets/238558/77bfaeeb-0a97-43f6-b807-0f625d1ebfae)

If I make scrollbar in the red area visible via script, the framerate is good. Otherwise, there is a dirty subview because of the invisibility and non-zero area. As far as I can see, some Python statement `SetVisible(False)` on a scrollbar will only touch the flags but not change the size to some 0 (as in `ToggleScrollbar`) but that's not the case in here, so there is probably something else.

**Comment by MarcelHB** [comment]
So yeah, that's the reason apparently: https://github.com/gemrb/gemrb/blob/1220c1109ba4ecdfabc404c0ddbae3b1a147b550/gemrb/plugins/CHUImporter/CHUImporter.cpp#L381-L384

What to do? I'd say that that `SetVisible` on a scrollbar should be overloaded or something to match criteria introduced by #2087 like putting the dimension to 0.

**Comment by bradallred** [comment]
Right, and that probably makes sense with IWD2 and PST because we cant just assign our own scrollbars due to the CHU background and their placement relative to the `TextArea`. We probably ought to have a flag to track when we are managing the scrollbar vs when it's external so we don't toggle the visibility in those cases.

But it also seems like there is a bug with the visibility toggling, because it looks like the `ScrollBar` _should_ be visible in your example, no?

> I'd say that that SetVisible on a scrollbar should be overloaded 

I disagree; I don't think that is something that should be overloadable. If something did want to invoke such behavior we have `View::FlagsChanged` already. But changing the dimensions shouldn't be necessary, we do it for the other case because the ContentView is also resized to take advantage of the space when the content is short.

That said, perhaps the `IsVisible` check in `DirtySuperViewRegions` could be removed if `View` just called `superView->MarkDirty()` when visibility changes.

**Comment by bradallred** [comment]
> But it also seems like there is a bug with the visibility toggling, because it looks like the ScrollBar should be visible in your example, no?

I guess that scrollbar is for the list on the left? I don't understand how that would get hidden since it doesn't seem attached to a `TextArea`. Something in the GUIScript? Seems like it ought to be disabled, not invisible.

**Comment by MarcelHB** [comment]
> But it also seems like there is a bug with the visibility toggling, because it looks like the `ScrollBar` _should_ be visible in your example, no?

No, there is nothing to scroll down. The original displays, not even looking disabled or anything like it, but it's useless in this case.

> I guess that scrollbar is for the list on the left? I don't understand how that would get hidden since it doesn't seem attached to a `TextArea`. Something in the GUIScript? Seems like it ought to be disabled, not invisible.

No, it's just that in CHUImporter, and nothing apparently ever requests its visibility again.

https://github.com/gemrb/gemrb/blob/1220c1109ba4ecdfabc404c0ddbae3b1a147b550/gemrb/plugins/CHUImporter/CHUImporter.cpp#L376-L385

> That said, perhaps the `IsVisible` check in `DirtySuperViewRegions` could be removed if `View` just called `superView->MarkDirty()` when visibility changes.

Yeah, I'll give it a try.

**Comment by lynxlynxlynx** [comment]
Re CHUImporter: can't we just delete that branch and call SetVisible on the ones that need it from the python side?

**Comment by bradallred** [comment]
> Re CHUImporter: can't we just delete that branch and call SetVisible on the ones that need it from the python side?

not exactly, the `ctrl = sb` bit is probably relevant. You'd also then have to track down all the places it occurs. Is there an easy way to do that?

**Comment by lynxlynxlynx** [comment]
Ah, yes, didn't see that — obviously I meant just the SetVisible call. But yes, if you're asking if it's easy to find scrollbars with bad links, that's easily scriptable with iesh (just annoying, since it's still on py2). It just feels like the hiding would be a rare need.

**Comment by MarcelHB** [comment]
Looks good this way.

**Comment by lynxlynxlynx** [comment]
Are you sure it's the same reason? I've removed all the problematic controls. On the other hand, the hack for #2087 might be wrong, that's why #2099 remains open.

**Comment by MarcelHB** [comment]
I just replayed some of the scenarios and observed the same as before, e. g. journals. Will investigate when I find time.

**Comment by MarcelHB** [comment]
The whole game has a handbrake right now that accounts for a 60% performance penalty (that you won't notice on fast computers and 144 Hz): IWD2 main menu for example, and thus probably everything of type `Window`, has some ever-redrawing loops as there is a scrollbar around, since Window-is-a-ScrollView-has-ScrollBars, and window is 800x600, its scrollbar is 0x600 but _not_ set invisible, and the heuristics check is height < 400.

**Comment by MarcelHB** [comment]
So these previous fixes aren't bad, but keeping windows dirty and redrawing them constantly just hid another bug that's getting unearthed now and causes grayed windows to become black after just a couple of frames: https://github.com/gemrb/gemrb/blob/e7ad4581436fba844a54706beb1546f3792c10a3/gemrb/core/GUI/WindowManager.cpp#L655-L659

If nothing is dirty any more, `win->Draw()` remains still as intended, but the gray is applied regardless. Will try if this can be moved to `DrawSelf` or something so it's part of all other checks.

**Comment by lynxlynxlynx** [comment]
Ah yes, I saw that as well. We use it for example to disable access to the inventory if the pc is confused, held, asleep or otherwise unorderable (plus the spellbooks, which looked fine before the release).
