### ISSUE TITLE
 IWD2: Cleric domain spell counters also corrupting

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2173]
#### Bug description

Similar to #2157, I started to notice that with a level 6 cleric + level 1 fighter, the counters of domain spells of level 3 also explode. Here are three instances of _Find Traps_ and one instance of _Dispel Magic_, with many millions in the counters.

Leading more and more to hanging UI and slow saving.

#### Screenshots

![iwd2_domain_level4](https://github.com/user-attachments/assets/b12f0db6-e3f9-449b-af54-5864bb93bb96)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Pretty sure that's just a buggy save, from before the fix. Is that a cleric of Oghma?

**Comment by lynxlynxlynx** [comment]
Hmm, there is some problem indeed. I leveled up a fresh priest and after going to level 5, my GUISPL count for level 3 domains went to -3, a different spell is shown as memorized and it has 4 memorizations. Then doubles each save.

Same problem, somehow the same spellbook got two copies of the spell, so PutIWD2Spellpage messes it up. It's not a problem of limiting to a spellbook, since the two level 3 domain spells are not present in the main one. Need to check how granting domain spells manages to evade me making LearnSpell idempotent wrt known spells.

**Comment by lynxlynxlynx** [comment]
Here in another case, the problem is that when looking up protection from evil, the priest version is found first (when learning from scroll), so then the actor does have two copies in different spellbooks. A related, but separate issue, I guess.

**Comment by lynxlynxlynx** [comment]
Ok, as for Protection from evil scroll, it itself specifies learning the priest version and the original happily accepts that. So we could hit the same situation with original saves, so another reason we have to make it be able to live alongside other copies.
