### ISSUE TITLE
 IWD2: Party undressing at the sight of Sseth's eye

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2187]
#### Bug description
When facing the eye of Sseth (AR6103) that is supposed to cause PCs to run away, they not only do so, they leave their whole stuff on the ground. That's bad since you can't get it back this way.

#### Screenshots

![iwd2_sseth](https://github.com/user-attachments/assets/b3a36f30-0a4a-4334-a5d8-2af3dd6f4b95)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
it's by design in 61SSEEYE.BCS:
```
IF
	See([GOODCUTOFF],0)
	!IsAnimationID(LastMarkedObject,"""""Mummy, Histachii""""")
	CheckStatGT(LastMarkedObject,1,ENCUMBERANCE)
THEN
	RESPONSE #100
		DropInventoryEX(LastMarkedObject)
END
```
It was probably added, so you don't overwhelm the histachii, which will have a lower carrying capacity. But, for us the weight check will practically always be true, since we store the weight there, not just encumbrance. This part needs testing in the original.

**Comment by MarcelHB** [comment]
In the original game, nothing is put on the ground and everything else is also kept wearing.

**Comment by lynxlynxlynx** [comment]
But what if you are encumbered?

**Comment by MarcelHB** [comment]
I see no difference.

**Comment by lynxlynxlynx** [comment]
Sorry, I guess it checks for full encumbrance, where you can't move. But that'd be a bizarre corner case to be able to get there and get over the limit before the eye sends you away. Perhaps easier with groups.

CheckStat and co should just be crippled for this stat, since we use it differently. And it's only used twice in all games:
```c
scripts/iwd2/61sseeye.baf:56:  CheckStatGT(LastMarkedObject,1,ENCUMBERANCE)
scripts/iwd2/61ziltyo.baf:242:    CheckStatLT(MyTarget,1,ENCUMBERANCE)
```
One is this useless one, the other just a little gem in the ai scripting of Ziltyor, so fine as well (it's even in an Or() check).
