### ISSUE TITLE
 BG2: Rod of Resurrection does not work

### ISSUE THREAD

**Issue by jpalus** [gemrb/gemrb#2193]
#### Bug description
So I had this Rod of Resurrection for a while now but was never able to use it successfully. Always blamed it on my lack of skills or some unfortunate conditions. Today finally made a test comparing original engine and GemRB with same save and it worked flawlessly first time in the former while it failed in the latter.

#### Steps to reproduce
1. Choose your companion which will be sacrificed in the name of debugging
2. Slash him/her
3. Try to resurrect companion with rod

#### Expected behavior
Companion is brought back to life and charges counter decreases (none of it happens).

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [X] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
I guess you're supposed to use it on the portrait? What happens in GemRB?

**Comment by jpalus** [comment]
Used it on portrait in both cases. In GemRB absolutely nothing happens.

**Comment by MarcelHB** [comment]
I had a resurrection issue myself some minutes ago, using a cleric spell, but not sure if related: portrait didn't work. Location on map does, despite the cursor being gray.

**Comment by lynxlynxlynx** [comment]
The place to start investigating would be `GameControl::PerformActionOn`, where it joins the usual item use attempts, probably ending up in Actor::UseItem or UseItemPoint. Maybe it gets filtered out somewhere, since the target is dead — only a few spells can work on them.

**Comment by jpalus** [comment]
It's this condition which disallows it:
https://github.com/gemrb/gemrb/blob/96a0f04cc2c764e07b06f27f7ade12c493282e56/gemrb/core/GameScript/Actions.cpp#L6793

After removing it all worked fine. Don't have enough knowledge of how to special case item to be allowed on `IE_AVATARREMOVAL` so can't provide the fix myself.

**Comment by lynxlynxlynx** [comment]
That would mean the pc died of a chunking death (normal, ice or stone). Are you sure this is resurrectable in the original?

**Comment by jpalus** [comment]
I'm not really sure how to tell the difference between deaths, does it have a chance of occurring if death is by plain arrows? Cause it's the same then too. Although sometimes I've noticed companion avatar completely disappears and sometimes not, I don't remember if it was original or GemRB. Obviously I can't resurrect if picture is missing. Is there any correlation here with `IE_AVATARREMOVAL`? Cause I have `IE_AVATARREMOVAL` with avatar/picture still on.

**Comment by lynxlynxlynx** [comment]
It can be from any physical damage type, it just has to deal enough damage (to get you to -10 hp or somesuch). The avatar explodes, so you can see it (if you have Gore on in the settings).

This might indeed be a different bug, like you say, we don't kick them out of the party, so the portrait stays. Look at `ChunkActor`, that would be the place to call `LeaveParty` from.

**Comment by jpalus** [comment]
Hm isn't `IE_AVATARREMOVAL` set in all death cases?
https://github.com/gemrb/gemrb/blob/96a0f04cc2c764e07b06f27f7ade12c493282e56/gemrb/core/Scriptable/Actor.cpp#L5684-L5690

**Comment by lynxlynxlynx** [comment]
Ah, yeah, it's more complicated. Persistent (global) actors are those stored in the GAM structure, so the party, familiars, potential party members and anyone else that gets made persistent manually. At the same time you want to be able to raise dead pcs in stores, so we make them follow the party through areas, so when you do it, they apparate in front of you, not where they were slain. I'm pretty sure this is why this crude IE_AVATARREMOVAL setting was added, so you don't see a corpse whenever you enter a new area.

But ideally the corpse would still be visible in the area it was created in, just not the others. So I guess one workaround could be to store the area of death in the actor and when loading them in new areas, if the names don't match, remove them. Since they're global actors, they should still be findable by scripting and effects, though perhaps some tweaks would be needed.
