### ISSUE TITLE
Check ambient rolloff works

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#2241]
It seems we currently just cut off ambients:
https://www.gibberlings3.net/forums/topic/38983-setup-ambient-sounds/#comment-344795

So we need to:
- [x] check how the originals behaved (IOW do we need a game flag or can we just improve?)
- [x] add/fix our rolloff regardless
- [x] check the attached wav problem
- [x] check the attached ogg problem

**Comment by MarcelHB** [comment]
There was always a cut off for ambients as far as I remember. I smoothed the rolloff somewhat, but yes, that's not optimal yet and requires to work with some limitations of OpenAL.

OGG has no stereo-spatial workaround yet. Not sure what's wrong with WAV file.

**Comment by MarcelHB** [comment]
In PST and BG2 original, it looks like a linear roll-off, with the radius roughly reflecting the pixels away from the camera center until it goes silent, i. e. something at the horizontal edge with radius 400px at 1024x768 is almost inaudible. So unless somebody spots a significant difference, one model should fit them all.

I'll review what we are doing with the params for OAL here.

**Comment by lynxlynxlynx** [comment]
IIRC OpenAL uses a non-linear model, something we opt-in with a setting. Doesn't appear our parameters give a gradual enough function though.

**Comment by MarcelHB** [comment]
While testing my settings, I found another bug: _Stereo_ ambients, like the crystal sound in AR1202 in PST never get their spatial flag set.

**Comment by MarcelHB** [comment]
One side-question because it kept me busy for some time. Is this is a good idea? https://github.com/gemrb/gemrb/blob/757558d4ce5507ac07046d889deae26f7d3b0a6a/gemrb/core/ResourceManager.cpp#L189-L190

in contrast to swapping these two lines? I was trying to load an OGG file for replacing an existing ambient file (WAV) by putting it into `override`. Problem is now that some other reader associated to the current `type` comes first (`ACMReader`), and will find some suitable WAV file in the `chitin.key`. Even renaming the OGG file to `.wav` and having precedence didn't help much since `ACMReader` refuses to ingest this correctly and again ends up in the shipped version.

**Comment by lynxlynxlynx** [comment]
I think we can swap them without much worry. I suspect it might cause more disk lookups, but I doubt that's significant.

**Comment by MarcelHB** [comment]
Ok, but I'll leave like this for now, I don't want to introduce unforeseen side effects just for some testing shortcuts.
