### ISSUE TITLE
[enhancement] Convert `Point` from short -> int32_t

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#232]
There are several issues stemming from the use of the `short` type in `Point`.

1. incompatible with `Region` and `Size` (they use `int32_t`)
2. cannot cast to `SDL_Point` which is a performance bottleneck in some places (issue bradallred#123)
3. IWD2 (possibly EE) uses 4 bytes for them
4. PST Journal must be truncated due to overflow
5. some controls `WorldMapControl`, `ProgressBar`, possibly others are encoded in the CHU with them

there is also a lot of code that could be cleaned up where we want to assign a point/size to a `Region`, but cannot because the use of short prevents defining `Region` in terms of a `Point` + `Size`

please wait till after #95 to avoid conflicts and possible subtle bugs on merge

**Comment by bradallred** [comment]
note to future self: search for explicit c style casts to `(short)`

**Comment by bradallred** [comment]
while we are at it and having to change/scrutinize the construction sites... we may as well make `Point` conform to `std::is_trivial` as it is not much extra work on top of this.

**Comment by kmfrick** [comment]
I'm not sure if this is the right place to point this out, but there are two different kinds of `Point`: those using searchmap coordinates (where pathfinding is done) and those using navmap coordinates (where e.g. scriptable positions are memorized). 
The searchmap is a downscaled version of the navmap (16x on the x axis and 12x on the y axis), which makes sense for a pathfinder and doubly so with the new one I've been working on for too long which decouples pathfinding and actual movement.
However, while working on said pathfinder I often inadvertently passed navmap points to functions expecting searchmap points and the reverse, causing much woe. 

I added a couple typedefs and used tons of Hungarian notation in my code to make it easier to understand, but while I'm at it, post-merge of my PR, I could split Navmap and Searchmap points and add automatic conversions or something like that (Navmap to Searchmap is `x/16` and `y/12`, while Searchmap to Navmap is `x * 16 + 8` and `y * 12 + 6` because the searchmap points map to centers of the navmap). I know which functions expect what pretty much by heart now and it would remove quite a lot of `q.x = p.x / 16 ...` and so on.

**Comment by lynxlynxlynx** [comment]
Besides the increase in memory use, I don't see a connection.

**Comment by kmfrick** [comment]
Okay, disregard the post then, we'll discuss this after I'm done with that pathfinder

**Comment by kmfrick** [comment]
This will also be useful for functions that take a `Point` argument so you can just pass an initializer list instead of creating a variable.

**Comment by bradallred** [comment]
yes, fixing this is definitely the top of my list after all the invasive merges are complete for a bunch of reasons. Lots of functions that take `int x, int y` can just use `Point` too.

**Comment by bradallred** [comment]
The PR only makes the change from `short` -> `int` I cannot remember how we hacked the PST journal to truncate. We should be able to reverse it tho.

I also don't immediately recall which data structures need to be updated for IWD2 to actually read the full point (probably the bytes are 00 anyway or we would have hit this by now) it might have just been scripting which should be good now. possibly some importers read 2 bytes, skip 2 bytes, read 2 bytes, skip 2 bytes for a point, but I suspect if thats the case those skipped bytes are just 00 anyway or else we would have discovered breakage earlier.

**Comment by lynxlynxlynx** [comment]
I don't know where the iwd2 info is from, but the extra word could also just have been padding.

**Comment by bradallred** [comment]
@lynxlynxlynx the IWD2 stuff apparently comes from [AREv9.1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v9.1.htm) where the vertices are 4 bytes. It's true that they can't possibly use the upper 2 bytes since all other coordinates and the area size is limited to 2 bytes.
