### ISSUE TITLE
[bug] BGT Each spell from the wizard spellbook is memorized upon rest

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#239]
**Describe the bug**
Each spell from the wizard spellbook is memorized upon rest. The lower the level of the spell the more it memorizes the spell. It doesn't add new slot spells. You can remove the spells manually. 

GemRB version: 

**To Reproduce**
Hard  case. It happens on any new game with my mod setup probably doesn't happen on vanilla BG2/BGT - or someone else would have reported it already.

Video showcasing the bug:
https://youtu.be/lFc_1GSzG7o

Modlist:
https://pastebin.com/6mST3xgU

I had this bug before but rolling but to older safe worked now it doesn't.

**Comment by caillean7** [comment]
Same with my BG2 installation. Isn't this what @lynxlynxlynx meant with #219?

**Comment by cygarniczka** [comment]
It's a relief knowing it is not likely related to me having godzillion of installed mods. :)

**Comment by caillean7** [comment]
No, I have an unmodded BG2 installation, the problem affects this one, too. So it's not a mod issue.

**Comment by lynxlynxlynx** [comment]
This is definitely a regression, but yeah, probably #219 did it and now your actor is screwed.

**Comment by cygarniczka** [comment]
> #219 did it and now your actor is screwed.

So the only way is to go back to older save and use older gemrB fom more than 8 days ago when #219 thread was created?

> If chargen + sleep is enough to reproduce, even better.

Yes it happens with newly generated character. With ToB new game I reproduced the bug.

**Comment by lynxlynxlynx** [comment]
I don't know when this started happening, but I have a pretty recent suspect. So I can't tell you which build works and which not.

Please check this one:
https://sourceforge.net/projects/gemrb/files/Buildbot%20Binaries/Windows/AppVeyor/gemrb-win32-d9ac315.zip/download

**Comment by caillean7** [comment]
I checked with a git version I downloaded on July 15th, the problem is not present there. And, good news concerning save games, I removed all the memorized spells, rested, and ended up with the right amount of spells afterwards.

**Comment by cygarniczka** [comment]
Thanks I checked the windows build - gemrb-win32-6656617.zip version from the 23rd July and the problem is not there even on my today's save.

**Comment by lynxlynxlynx** [comment]
that still leaves 170 other candidates, so please try the one I suggested.

@caillean7 It's even easier for you. Are you willing to do a git bisect run? That would basically test a minimal set of revisions after the chosen one (7 or 8 builds in this case), to prove where the problem started. See basic bisect section here: https://git-scm.com/docs/git-bisect (you'd use 6656617 instead of v2.6.13-rc2 )

**Comment by cygarniczka** [comment]
Thanks I checked the windows build - gemrb-win32-6656617.zip version from the 23rd July and the problem is not there even on my today's save.
///
EDIT: The last windows build that didn't have issue was gemrb-win32-d72c28d from July 28th. The next build gemrb-win32-f03267c even hints at the issue with L added to number of the choice dialogue.
![choice numbers L](https://user-images.githubusercontent.com/17316115/64988152-d3b51780-d898-11e9-9086-df99961e670a.jpg)

**Comment by lynxlynxlynx** [comment]
Ok that narrows it down a bit, but there are still multiple commits per build. The L thing I know exactly when it was introduced and fixed and is completely unrelated. If @caillean7 can save me doing the bisection myself, we'll get the exact culprit faster.

**Comment by cygarniczka** [comment]
I am just glad this issue does not bake itself into the savegame.

**Comment by caillean7** [comment]
I'm on it.

**Comment by lynxlynxlynx** [comment]
great, thanks! Once it narrows down to a single commit, there's one more step to verify it is to blame. Try reverting that commit (git revert commit-hash) and building and testing once again. If the revert fails due to conflicts, don't bother, since it could be hard to fix, otherwise you get to disprove or approve the bisect findings — reverting (removing) the commit should kill the bug.

**Comment by caillean7** [comment]
Okay, seems it was introduced with https://github.com/gemrb/gemrb/commit/fed075df8cf9749467e1df67d5dd9bdd8a2e624c.

**Comment by lynxlynxlynx** [comment]
Are you sure? For mages the passed value is the same. :S

**Comment by caillean7** [comment]
Huh - with https://github.com/gemrb/gemrb/commit/d72c28dc8b2a1cec63137525aa34154e310f0399 the issue is not present, but with https://github.com/gemrb/gemrb/commit/fed075df8cf9749467e1df67d5dd9bdd8a2e624c it is.

**Comment by lynxlynxlynx** [comment]
Ok, I understand. This commit was ok, since it fixed a bug. In doing so, it exposed an older bug and that's why we have the problem. All sorts of spellbook settings are tried, also the cleric and sorcerer one, so that's where it probably goes wrong in the end. But the main reason is sooner, those changes shouldn't be running at all.

**Comment by caillean7** [comment]
Well, my 'expertise' with these things is fairly limited, but if there's some more test stuff I can help you with, give the word.

**Comment by lynxlynxlynx** [comment]
I have to fix it first, but thanks you two, you save a lot of my time already. :)
