### ISSUE TITLE
[bug] BG2: Dialogue issue with NPCs' PID

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#246]
**Description**
If an NPC has Player Initiated Dialogue, it might happen that dialogues do trigger, but then you get to see only the PID, and not the right lines. I've seen this happen at least with Weimer's Solaufein and Valygar in a quest from the Corthala Romantique mod. You mentioned all this dialogue stuff calls on a common function, so it's probably related to #236. Here the details from the Valygar case:

Valygar is supposed to initiate dialogue with Player1, script- and condition-wise all is fine. From Valygar.bcs:
```
IF
	Global("H#LeoQuest","GLOBAL",8)
	!See("H#LEON")  // Leonora - Leonora De Vallenzzi
THEN
	RESPONSE #100
		Dialog(Player1)
END
```
Using StartDialogueNoSet instead of Dialog since it's more commonly used in scripts doesn't change anything btw.

Then what's supposed to happen from ValygarJ.dlg:
```
IF ~Global("H#LeoQuest","GLOBAL",8)~ THEN BEGIN WhatIsIt
SAY @81
++ @82 + TheQuest9
++ @83 + TheQuest1
...
```
Instead what shows up is the PID:
```
IF
~IsGabber(Player1)
Global("H#NoFlirt","GLOBAL",0)
CombatCounter(0)
OR(2)
...
```
Ending the talk will cause him to re-initiate it over and over again, you get caught in a loop and the quest can't be finished. I recently played through it in EE to confirm it's not the mod. Also, removing the PID part from his dialogue script does the trick, while moving it to the bottom of the script didn't.

**GemRB version**
0.85

**To Reproduce**
- Install the mod from G3
- a save game with Lavok already dead should trigger the quest after one in-game day. Otherwise set Global "LavokDead" to 1. Chapter must be below 7. Rest 3 times to pass some time.

**Comment by lynxlynxlynx** [comment]
Is the second script snippet from a script or the dialog? Can you pastebin the relevant stuff?

**Comment by caillean7** [comment]
The 2nd and 3rd ones are both from ValygarJ.dlg.

[PID from ValygarJ.dlg](https://pastebin.com/xQRMCQ2U)
[Quest related stuff from ValygarJ.dlg](https://pastebin.com/b4fMKbbt)
[Script stuff](https://pastebin.com/3msntEn6)

**Comment by lynxlynxlynx** [comment]
In which order does the mod append, does the pid stuff come sooner in the file? I do hope so.

Your though that it may be the same bug has some merit. If you negate the IsGabber check or change the code to check for IsTarget instead of IsSpeaker, you should get farther.
https://github.com/gemrb/gemrb/blob/3e0aedb88549adbc2beb30428fadfdedce58cd1a/gemrb/core/GameScript/Triggers.cpp#L316
It's clearly wrong, but a good test.

**Comment by caillean7** [comment]
Like mentioned in the initial post, I already checked the order of this stuff in the dlg file. If the script is parsed from top to bottom the first thing that matches conditions should trigger - that's what I thought. So I cut & pasted the PID block to the bottom of the script, but it made no difference. Only removing it completely made the dialogue work correctly. And, you're correct, I changed that line in Triggers.cpp, now it works.

Heh, I'm just guessing since you mentioned a common function BeginDialog. While it this works in the vast majority of cases, it goes awry in a tiny portion of mod dialogues. I have another example, in the very Valygar quest of the above case. Question is, do you want a separate issue, do you you prefer it mod-wise - should I just add it to this issue, or some meta-issue referencing all this potential Begin Dialog stuff?

**Comment by lynxlynxlynx** [comment]
Let me investigate a bit first, but good to know the previous thinking was correct.

**Comment by caillean7** [comment]
Sure :) Let me know if you need more examples, I could probably come up with a couple more of these Dialogue (in the broadest sense) problems.

**Comment by lynxlynxlynx** [comment]
Something from vanilla would be ideal, so I wouldn't have to go install a mod.

**Comment by caillean7** [comment]
I've also had something with Nalia at her father's funeral - you don't happen to have a convenient save game?

**Comment by lynxlynxlynx** [comment]
I was quite lucky, so yes. Took only one rest for the chain to trigger. Talked to everyone there and all seemed fine.

**Comment by caillean7** [comment]
So mine was probably caused by a mod. The Roenalls wouldn't recognize Nalia was in the party.

**Comment by caillean7** [comment]
I just came across another one, with Mazzy after defeating the Shade Lord. This time I tried in an unmodded game, too.

After the Shade Lord is dead, Mazzy is supposed to say:
```
IF WEIGHT #6 /* Triggers after states #: 480 539 569 579 580 581 even though they appear after this state */
~  Dead("SHADEL")
Global("ShadowLordDead","GLOBAL",1)
Global("MazzyComment","AR1400",1)
Global("MazzyAltar","GLOBAL",0)
~ THEN BEGIN 0 // from:
  SAY #24048 /* ~It is done, though the vengeance is empty. Patrick and my companions had to serve in death as slaves to the Shade Lord.~ [MAZZY77] */
  IF ~~ THEN REPLY #24051 /* ~They died with honor regardless of what the Shade Lord did to them afterwards.~ */ GOTO 3
  IF ~~ THEN REPLY #24052 /* ~Only the finest are meant to survive. These brave companions of yours didn't survive because they were weak.~ */ GOTO 2
END
```
Instead she turns to Charname, so it seems to trigger okay, but the message window just shows "Mazzy - has nothing to say to you". Perhaps this is something vanilla you can reproduce?

**Comment by lynxlynxlynx** [comment]
The first game I tried was modded and this fired up fine. I did get a "nothing to say" at the end though, after the fade out from supposedly doing the inscription on the altar. But it was Nalia, the closest pc, doing the talking in the second half.

The first thing is consistent, "Know, noble heroes ..." then fires a StartDialogueNoSet([PC]). Same for the cutscene triggering the dialog, so at least it's kinda ok that Nalia was the second interlocutor. But not really, NPCs have a mind of their own, so you shouldn't be able to talk in their stead.

**Comment by caillean7** [comment]
I have an installation with the Mazzy friendship mod installed (well, amongst others), on this one the first part triggers as well, and the bit after the inscription won't work, just with your game. And the unmodded game won't trigger the alter inscription talks at all.

The thing with Nalia doing the talking is consistent with original engines, I'm pretty sure. So if you were to fix that, it would actually be an enhancement.

**Comment by lynxlynxlynx** [comment]
Nah, that would be silly, since it clearly targets all pcs. It was enforced only in PST.

So the speakers end up switched in InitDialog, maybe. The problem isn't obvious though, as looking for the correct dialog state ("Could not find a proper state" in console) doesn't find one for the other actor either. `mazzyj` is the dialog file in question:
```
IF ~~ THEN BEGIN 102 // from: 4.0
  SAY #42118 /* ~Know, noble heroes, that you are not forgotten. May this altar always stand as a monument to your unselfish courage. Farewell! <CHARNAME>, the inscription if you would.~ */
  IF ~~ THEN DO ~FadeToColor([30.0],0)
Wait(2)
FadeFromColor([30.0],0)
StartDialogueNoSet([PC])~ EXIT
END

IF WEIGHT #8 ~Global("MazzyAltar","GLOBAL",2)~ THEN BEGIN 103 // from:
  SAY #42119 /* ~It is done and the world of the living continues. We should retire to Imnesvale, friend, and inform the good Minister that the shadow is lifted. Let us go.~ [MAZZY81] */
  IF ~~ THEN DO ~SetGlobal("MazzyAltar","GLOBAL",3)
ActionOverride("uhrang01",StartDialogueNoSet([PC])~ EXIT
END
```
So it's the dialog that starts another dialog ... with the same people (why not a goto 103?). Looks silly, but oh well.

MazzyAltar is already 3 though, but that should be from the area script, since the problem is in the previous state already — otherwise "It is done..." would get printed.
```
IF
  Global("MazzyAltar","GLOBAL",2)
THEN
  RESPONSE #100
    TriggerActivation("Altar",FALSE)
    TriggerActivation("AltarMaz",TRUE)
    SetGlobal("MazzyAltar","GLOBAL",3)
END

IF
  Global("MazzyAltar","GLOBAL",0)
THEN
  RESPONSE #100
    TriggerActivation("AltarMaz",FALSE)
    TriggerActivation("Altar",TRUE)
    SetGlobal("MazzyAltar","GLOBAL",3)
END
```
So the first block must be the setter, since the second would break dialog earlier. To end my late train of thought, it seems the area script fires in between and thus the condition isn't true anymore and no match is found. Resetting the value to 2 after the breakpoint then finds the correct state and the reply is given.

The dialog is set to pause properly, but of course the script actions it runs can't work without time passing, especially Wait. So I'll just conclude: WTF, and go to sleep.

**Comment by caillean7** [comment]
Pleasant dreams.

**Comment by lynxlynxlynx** [comment]
The new area (switched earlier from the shade-infested in the cut30b cutscene) gets one or several ticks in, so that's where it goes wrong. The thing is we even have a game flag (since 6e92a8ab9a38) to toggle whether area scripts should run in cutscenes or not and it's already off for bg2. So where does the area get its time?

**Comment by caillean7** [comment]
It takes a second or so after the cutscene for the dialogue to start. Could that be enough time? And, I noticed it plays the day / night video, too, so could that block from the area script run while the video runs?

**Comment by lynxlynxlynx** [comment]
cut30b runs DayNight after teleporting peeps away, so there's a lot of time passing. But it's still in a cutscene, so it should be fine. I think more gritty details need to be investigated — do we get one tick in already at creation, somehow bypassing the update check? I doubt it, but it could easily be an off-by-one error somewhere. One tick too many is enough.

The new area script needs to run in between the cutscenes for the chain to work:

1. old area (ar1404) runs cut30a on enemy death
2. cut30a teleports everyone to the new area (ar1400) and ends
3. ar1400 runs cut30b (so it has to be running)
4. cut30b starts a dialog
5. dialog sets MazzyAltar to 2 and starts cut30c
6. cut30c starts a dialog
7. dialog starts the same dialog (see above)
8. dialog doesn't find the correct state due to MazzyAltar=3 by the area script interference

Individual cutscenes end when the dialog finishes. So the problem starts somewhere from 5 onwards. Time to do some timing and the annoying tracking of MazzyAltar changes.

**Comment by caillean7** [comment]
The whole timing seems to differ depending on the installation, though. If I try this with an unmodded one, the whole Mazzy dialog doesn't work. So the dialogue would get started in 4., but 5. wouldn't work at all ("Mazzy - has nothing to say to you"). Your installation is modded, right? Did you try a vanilla game?

Well, at least this thing seems isolated; the other problem cases (Alternatives, Valygar, Amber) don't have any area or other scripts affecting variables.

**Comment by lynxlynxlynx** [comment]
I only have the fixpack and some unrelateds on that one. But the fixpack specifically mentions fixing some of the problems, see _Miscellaneous Mazzy Dialogue Errors_:
https://www.gibberlings3.net/subpages/bg2fixpack/docs_dialogue/

But you're right in the sense that trying to find a clean reproducer just showed a different bug.

**Comment by caillean7** [comment]
I see. I'll add the Fixpack to my 'unmodded' installation I use for testing then, no need chasing already fixed bugs.

**Comment by lynxlynxlynx** [comment]
I've opened a separate bug for the Mazzy stuff. Please open a new one and include all the initial info in the opening post (including the isgabber mod helping), so the PID investigation can continue.
