### ISSUE TITLE
[subviews] Blending bug in animated overlays

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#257]
**Describe the bug**
Found some animated overlay not blended or clipped correctly. This is a regression.

**To Reproduce**
1. Start BG.
2. Go to AR0125 (final battle)
3. Head towards Sarevok's throne.

**Expected behavior**
These purple lamps or fires should not be sorrounded by black.

**Screenshots**
![bug_subviews_bg1_blending](https://user-images.githubusercontent.com/238558/65838707-421cbf80-e306-11e9-9c8f-bf6e9bbb079a.jpg)

**Comment by bradallred** [comment]
> This is a regression.

From some other revision in this branch or from master? if its from master please don't bother confusing me 😉 

It's not helpful to know if something works in master and not here because otherwise you would open the bug on master. it _is_ useful to know if there is a regression on this branch, however. Please be specific for my sanity so i don't try bisecting trying to find out where it broke.

**Comment by MarcelHB** [comment]
When I write that, the it's a feature that works  as expected on `HEAD` of master and no longer works as expected in subviews. At the time of writing bug reports, I also have no idea if it's not implemented in the rewrite, or if something else actually broke that.

**Comment by bradallred** [comment]
> When I write that, the it's a feature that works as expected on `HEAD` of master and no longer works as expected in subviews. At the time of writing bug reports, I also have no idea if it's not implemented in the rewrite, or if something else actually broke that.

Right, I figured that, but labeling like that is confusing. As I said, if it works in master but not here don't bother labeling it a regression; I already know it works in master by virtue of the bug being tagged for this branch rather than master.

Please only tag bugs as regressions here only if they are a known regression within the branch so I can tell the difference between something that used to work here and broke vs something that just hasn't been implemented.

It's fine if you don't know; I don't expect you to do any bisecting :)

**Comment by bradallred** [comment]
I can see that at least some area animations still work properly. Are these even area animations, or are they attached to the lamps? it might just be we need to apply the same treatment as area animations have. Might be a data bug too (no alpha component).

**Comment by bradallred** [comment]
It would also be helpful if somebody with a working SDL 1.2 driver could check it. I suspect this is an SDL 2 thing only, but let's verify that.

**Comment by MarcelHB** [comment]
Ok, I skip that term for future bugs unless really sure it already once worked in subviews. ;)

From what InfExp tells me, It is not a background animation but an overlay. You can also see that in the fountains of candlekeep: The black area around needs to vanish, the blue water surface needs to blend.
![fountains](https://user-images.githubusercontent.com/238558/65840052-3506cd00-e314-11e9-8068-e459eceaca7e.jpg)

**Comment by bradallred** [comment]
Is the fountain in the middle of BG2 AR2000 somehow not the same type of animation? That was my original test case for these and it still works.

![image](https://user-images.githubusercontent.com/1126744/65840431-521cab00-e2d6-11e9-9511-4f3083bb8979.png)

**Comment by MarcelHB** [comment]
Funny thing, your example shows two overlapping types in InfExp, one is an overlay as mine (visually much cheaper than what you see here), the one on the screenshot is a background animation (AM2000A).

From what my Windows SDL2 claims, it uses D3D. Will check SDL1.2 in a minute.

**Comment by bradallred** [comment]
Does the fountain in my screenshot work for you on D3D then? or is it broken? I don't currently have BG1 installed to check the area you posted.

If it is broken on D3D it might be that we need to force D3D11 instead of 9. You can also try doing `SDL_SetHintWithPriority(SDL_HINT_RENDER_DRIVER, "opengl", SDL_HINT_OVERRIDE);` at somepoint before we create the renderer to force OpenGL and see if it works there.

**Comment by MarcelHB** [comment]
Ok, this is subviews SDL1.2, with interesting artifacts on the surface if you move around the viewport.

![fountains](https://user-images.githubusercontent.com/238558/65840678-23292800-e31c-11e9-9cb5-eff6c360a972.jpg)

I try to check BG2 in a minute

**Comment by MarcelHB** [comment]
The AR2000 area of BG2 looks good.

**Comment by bradallred** [comment]
Looks like our [custom blend mode](https://wiki.libsdl.org/SDL_ComposeCustomBlendMode) should be supported by all renderers except software (we use `SDL_BLENDOPERATION_ADD` only) So failing a bug in SDL all the renderers should work.

I'll try to find time to look into this next week.

**Comment by MarcelHB** [comment]
Yes, SDL is 2.0.10. Some versions before are a pain under Windows because of other reasons.

**Comment by bradallred** [comment]
setting the `RedrawTile` bool to false seems to work enough to get the same behavior as SDL 1.2. Anybody know what `RedrawTile` is for?

**Comment by bradallred** [comment]
it's clear to me now that the mask we are sending is not what I would expect. Is there some way we can extract `tile->anim[0]->NextFrame()`?

I'm beginning to suspect this sprite has an implicit color key and obviously SDL isn't going to know that.

**Comment by bradallred** [comment]
so at least the fountain area is trivially solvable by using a different blend mode for the mask... I'm just not sure how best to reconcile this case with the `SpriteCovers`. I need a way to distinguish the 2 cases.

![image](https://user-images.githubusercontent.com/1126744/65849400-83619f00-e307-11e9-89ed-d35e24cd5e3e.png)

**Comment by lynxlynxlynx** [comment]
With the sdl1 backend there is no black for the surroundings, but the blue is not there either. Something is definitely not cleared here too, since moving around leaves artifacts in the whole water part.

**Comment by bradallred** [comment]
trying to move to area AR0125 takes me to ulgoth's beard, so I can't verify this for you, but the fountain area works now.

**Comment by MarcelHB** [comment]
Looks good :+1:
