### ISSUE TITLE
[subviews] Cursor broken when entering map by map overview

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#284]
A bug I spotted in all of the games:

1. Open the map's overview.
2. Double-click where you want to jump in.

Now, the cursor is gray and you cannot do anything until manually switching into some other view (I pressed M twice to return).

**Comment by bradallred** [comment]
is this the same for all games, or another everything but BG2 thing?

**Comment by bradallred** [comment]
Nevermind, I see the code that closes the window is actually on the C++ side for some reason. Also, it appears GUIMA is a shared script anyway.

**Comment by bradallred** [comment]
IIRC, the window "OnClose" callback is purely a Python thing. I don't _think_ there is a reason for the `window->close()` being done in c++ instead of an action handler... If that is true then implementing a double click action handler that closes the window from python (and remove the C++ code) should fix this.
