### ISSUE TITLE
[subviews] BG load screen with minor glitch

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#288]
I am missing my Bhaal skull, mainly:

![bg_loading](https://user-images.githubusercontent.com/238558/66259721-c662bd00-e7b4-11e9-8119-1934772628df.jpg)

To be clear, there should be a gray picture of it, with glowing eyes when done.

**Comment by bradallred** [comment]
The problem with the glowing eyes is not BG1 specific... I actually wonder how, if at all, that part works on master since the progress bar completion callback is what both closes the window and changes the image.

The other issue is obvious when you enable `DEBUG_VIEWS`. The progress bar itself is covering it. Again this is something I don't know how it is supposed work in master (not saying it doesn't). This would work fine if the skull came after the bar in the CHU, but it does not so the gui gets built with the skull beneath the bar.

master has no concept of handling overlapping controls so I suppose this likely works by virtue of setting the image last forcing a redraw of that area. Presumably the original works on similar flawed grounds.

**Comment by lynxlynxlynx** [comment]
The skull is set up after the progress bar, the script could hardly be any simpler: gemrb/GUIScripts/bg1/LoadScreen.py

**Comment by bradallred** [comment]
> The skull is set up after the progress bar, the script could hardly be any simpler: gemrb/GUIScripts/bg1/LoadScreen.py

I have no idea why you think I don't know this

**Comment by bradallred** [comment]
I need to make an adjustment to the GUIScript plugin to return a new Python GView wrapper from `RemoveView` (when the delete parameter is false) so that we can add the view to a different `superview`.

For the window closing at the same time as updating the graphic, it looks like I added SetTimer which I can use to execute a timed callback from the progress bar end event handler so the window remains open for a second or so.
