### ISSUE TITLE
[bug] IWD1 Chargen: Illusionist restriction not enforced for Gnomes

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#312]
**Description**
Usually I complain about Gnomes being restricted, but now it's the other way 'round. It seems in IWD1 Gnomes can access any mage school on GemRB.

**GemRB version**
0.85-git

**To Reproduce**
- start character generation in IWD1
- choose Gnome for race and proceed to the class selection
- you should be able to choose generalist mage and all existing schools

**Expected behavior**
Restrict Gnomes like in the original (sigh)

**Comment by lynxlynxlynx** [comment]
This is a sad consequence of the fact that all games have different implementations of chargen. Through the years we managed to reduce code duplication significantly (especially since a lot of the logic is also needed for level-up), but the systemic differences remain. Hence sometimes bugs and features get added to only one game instead of all, since it's not automatic.

IWD1 has the whole process in one chargen.py file and should just do something similar as bg1 (one of the guicg*.py files handles multiclass choice).
