### ISSUE TITLE
[bug] proper range for modals

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#367]
Cleaning up computations for #145, I found we use sort of a pseudo-constant for modal range ... that looks too big.

How far did it work in the original. For example, how far horizontally&vertically can you stand away from a bard to hear her song? Or from an undead to turn it? Or from a trap to detect it, which might actually be different from the two before and can be tested in something other than iwd2.

**Comment by caillean7** [comment]
Move around, trying to find the edge of the range, make a screenshot and measure the pixels? I'd give it a go with BG2, if it's all the same to you. Also, should I measure from the center of the trap sprite, or the edge?

**Comment by lynxlynxlynx** [comment]
Good question! You could repeat the process once with a big trap, where that would matter, and once with one of those slivery small ones or container traps. Then if there's a difference in the measurement, we can check which is closest — edge distance, position, the centroid, one of the use points ...

**Comment by caillean7** [comment]
Will do (might take a couple of days though due to s****load of lawn work and stuff I gotta do this WE).

**Comment by lynxlynxlynx** [comment]
No rush here, thanks. I've already started the final playthrough and one other thing is bugging me more, it's just not written up yet.

**Comment by caillean7** [comment]
| Ability | Horizontal range | Vertical Range | Comment |
|---------|----------------------|---------------------|--------------|
| Turn Undead | ~ 219 px | 165 / 160 * | measured from center of caster's foot circle to center of wrecked skeleton |
| Bard Song | | | |
| Detect Trap | | | |


A question about the vertical: Depending on how the caster / target are placed, I'm getting slightly different results because of the perspective, I guess. E. g. if the priest is above the skeleton on the screen, the distance is a little higher than if I've placed him below the skeleton. Which value are you interested in, or both, or maybe the average?

**Comment by lynxlynxlynx** [comment]
Huh, I don't see why it should be different. How big is the difference? My bet is on inaccurate placement.

**Comment by caillean7** [comment]
Those 5 pixels. I tried each position twice, thought it might be due to isometry... ahem, I'll do some more tests then.

**Comment by lynxlynxlynx** [comment]
You're on the same axis; it's a tilted grid, not a converging one like with perspective. Otherwise it'd be also computationally stressing.

**Comment by caillean7** [comment]
My brain desperately wants to apply perspective, perhaps it's this. I still get those values, made 8 measurements and took the average of those. But now - if the horizontal values are both about the same, shouldn't the verticals be too?! For the bard song, I made 6 different attempts at each direction.

**Comment by lynxlynxlynx** [comment]
Your Turn Undead values look saner, yes. That'd be a range of 14.

**Comment by caillean7** [comment]
I'll retry the vertical Bard Song measurements tomorrow. Plus the horizontal trap distances (they differ too much, while the verticals are pretty consistent) :P That's tricky business.

**Comment by lynxlynxlynx** [comment]
Traps have many associated points, but if you get significantly different results from the exact same position, that's worrying.

**Comment by caillean7** [comment]
I've activated the Ctrl+9 cheat, which displays bounding boxes for the traps, and measure to the edge and to the center. The average however is not too far off the 219 px I've got for the other two abilities. I need to make more tests definitely, but my guess would be that all those abilities have the same range, around a 15 ft. radius. Maybe 16, that's what the supposed radius of the Bard Song in EE is according to something I read on the Beamdog Forums. The variation might be due to character positioning errors.

**Comment by lynxlynxlynx** [comment]
Ah, then that's good enough, since like you say, it's likely they all have the same range. But you're testing in some bg2, right?

**Comment by caillean7** [comment]
Yes, BG2, since I know this one best by far.

**Comment by lynxlynxlynx** [comment]
Ok, so only the trap stuff is really useful, since the rest uses projectiles. Or at least for us, since it did in the original; I think we check manually, so there's no need for more generic projectile code and it can remain limited to actors.

But iwd2's songs for example, those spells have single targetting, so we *have* to do it manually.

**Comment by caillean7** [comment]
Ah... I got this all wrong, have I? Only the trap stuff is to be tested in something other than IWD2 - the others need testing in IWD2?

**Comment by lynxlynxlynx** [comment]
It's good to know it's consistent, but yes, the main goal is to get rid of the constants VOODOO_FINDTRAP_RANGE and the one used by iwd2 songs (VOODOO_SPL_RANGE_F). All part of the same fireball work, double checking these also take the isometricity into account. I checked now and it's only iwd2 songs that need the workaround.

You figured it out for traps, which is half the work. :) 14 is half of the visual range default, so we'll use that to keep it dynamic. The other one might be the same as for the Shout() and Help() actions, which also use a constant right now and are tracked under #373 (3x visual range in EE).

**Comment by caillean7** [comment]
Gah, I'm so flustered at times. Ah well, but 14 fits with what I've got for the traps so far, added those results to the table.

**Comment by lynxlynxlynx** [comment]
Just went with the same value for iwd2.
