### ISSUE TITLE
[subviews] can't buy several items at once

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#370]
in the store, if you double click on a stacked item, the item amount window pops up. It doesn't work and gemrb soon crashes.

it's from an invalid id of 110. The original code used this as a temporary id to safely remap conflicting ids, but subviews does something different and it doesn't go well.

**Comment by bradallred** [comment]
I wonder if c0d5915 can be of use instead of using temporaries. Of course, I'm not yet sure what code is in question here.

**Comment by lynxlynxlynx** [comment]
It uses AliasSubviews or something like that (easiest to just grep for 110 in GUISTORE.py). This affects the whole store, you can't buy anything.

**Comment by bradallred** [comment]
GUI element 110 is either `STOSBARL` in PST or `STODONAT` in everything else. I don't see `STODONAT`  referenced anywhere else in that file so it seems like it was dropped in a merge or something.

However, I'm pretty sure that `STODONAT` is the donate button, so I'm not sure why that would cause an issue with buying stuff. The `STOSBARL` on the other hand is the left scrollbar so I can see that being an issue.

I'm supposing then the problem is just that GUI element 110 no longer exists? I'm supposing then you are in PST and that the problem is that we are deleting the scrollbar because we think it is associated with a TextArea. Am I close? :)

**Comment by lynxlynxlynx** [comment]
No, I'm testing bg2. The donation button is there, since I'm buying from a temple. See the initial report and master, this is all from subviews changes to the guiscript function. I guess all the indices weren't changed along with the code, if the goal was to remove the need for a 2-step process.

**Comment by bradallred** [comment]
changes to which GUIScript function? AddAlias is new.

It was a long time ago, but i did test temple donation and buying/selling in one of the BGs... probably BG1 since there is that temple right at the beginning. It is either a regression or a BG2 issue.

I still don't see where we reference `STODONAT` so that makes me this we can just remove that entry which would resolve at least the invalid control message with control 110, but that is unlikely to be an actual problem. Looking at the code we just print a message and continue so you can put whatever invalid entries in there you want. I'll try to reproduce it when I get home.

Those entries composed of '?' are in also need of updating or removal. What is control id 8 (or 11 in PST)?

**Comment by lynxlynxlynx** [comment]
What is ReassignControls in master maybe triggered the addition of AddAlias.

**Comment by bradallred** [comment]
Nah, just a happy coincidence :) AddAlias was added for the portrait/option/action/message windows. Since it operates on `View`s it just happens to work for any other GUI element as well. It didn't occur to me till much later that it suffices for cases like this too.

**Comment by bradallred** [comment]
this should be fixed. needs more testing. time for some sleep.

**Comment by lynxlynxlynx** [comment]
Seems fine
