### ISSUE TITLE
recheck some hardcoded sounds

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#374]
While researching on the forum, I came upon this old quote:
> And then finding out that they hardcoded special attack sequence sounds to crap like ankhegs and basilisks and wyverns (but nothing else)

So we need to compare with the original if we still lack some of them.

@skellytz also found some other hardcoded sounds, if I remember correctly.

EDIT: Also some other notes to recheck (one is the issue debated here, one doesn't apply ...) https://www.gibberlings3.net/forums/topic/34892-code-code-fixes-aka-stuff-we-cant-fix/?do=findComment&comment=311013

Potentially useful also the TobexAL fixes ("Sound:Disable Hardcoded BG1 Item Sounds [T]", "Sequence Sound Override Fix [F]") and table for "Externalise Animation Sound Reference Override", to make things more generic.
---
**Externalise Animation Sound Reference Override [M]**
Each animation sound 2da contains soundset information associated with each animation with the same 4-letter animation code (see reference ANIMSND.2DA). Unfortunately engine doesn't use ANIMSND.2DA, instead all 4-letter soundset filenames hardcoded to game code. Option externalises animation_id->sound_2da_filename mapping to ANISNDEX.2DA for override hardcoded values:
```
2DA V1.0
****
       File     Description
0x7101 MBAS2    BASILISK_GREATER
0x7200 MBER4    BEAR_BLACK
0x7202 MBER3    BEAR_CAVE
0x7203 MBER2    BEAR_POLAR
0x7401 MDOG2    DOG_WAR
0x7501 MDOP2    DOPPLEGANGER_GREATER
0x7702 MGHL2    GHOUL_GHAST
0x7B01 MWLF5    WOLF_WORG
0x7B02 MWLF6    WOLF_DIRE
0xA000 MWYV2    SMALL_WYVERN
```

**Sound:Disable Hardcoded BG1 Item Sounds [T]**
BG2 engine has one of BG1 legacy - some monster's weapons have hardcoded specific sounds. Same goal can be reached using new animation sound 2da files. Option disables hardcoded item mapping if this mapping will be rely on 2da files. For example hardcoded melee ANGHEG1.itm->ANKHG06.wav and range ANGHEG2.itm->ANKHG05.wav can be implemented in 2da format:
```
ATTACK or ATTACK_SLASH/ATTACK_BACKSLASH/ATTACK_JAB  ANKHG06
SHOOT                                               ANKHG05
```

**Sequence Sound Override Fix [F]**
Most animation types have hardcoded sequence overrides for animation sound 2da files. For example when Ankheg (animation_id 3xxx) does range attack, engine overrides SHOOT sound to READY. Fix removes most overrides and makes using sound 2da files more precisely

**Sound:Restore Creature Attack Sounds 1 [T]**
Engine has bug with Creature Attack[2-4] (0xe0-0xe8 offsets) sounds, it always play Attack1 sound only.
Restore sounds with mapping:
ATTACK1 – on slash animation
ATTACK2 – on backslash animation
ATTACK3 – on jab animation
ATTACK4 – on shoot/range animation

ATTACK4 wasn't used in original engine and has unknown original purpose, Skellytz introduced new mapping when need to set creature personal range weapon sound.

**Comment by skellytz** [comment]
These monster attack sounds are hardcoded to weapon items. They did this in BG1TotSC to play different sounds depending on whether it was a melee or ranged attack.

**Ankheg**
ANGHEG1.itm --> ANKHG06.wav
ANGHEG2.itm --> ANKHG05.wav

**Lesser Basilisk**
BASI**L**1.itm --> BASIL06.wav
BASI**L**2.itm --> BASIL05.wav

**Bug Note:** The actual items present in the game have a double L (BASI**LL**1.itm and BASI**LL**2.itm). This results in missing attack sounds.

**Greater Basilisk**
BASILG1.itm --> GBASI05.wav
BASILG2.itm --> GBASI06.wav
BASILG3.itm --> GBASI07.wav

**Ettercap**
ETTERC1.itm --> ETTER05.wav
ETTERC2.itm --> ETTER06.wav

**Wyvern**
WYVERN1.itm --> WYVER05.wav
WYVERN2.itm --> WYVER06.wav

**Winter Wolf**
WOLFWI1.itm --> WWOLF07.wav
WOLFWI2.itm --> WWOLF06.wav

**Comment by lynxlynxlynx** [comment]
Wow, that was exhaustive and fast, thanks! I guess they use scripts to decide what to equip.

Swing sounds are itemtype based, so it looks like we need yet another table to keep this clean and then use it in Actor::PlaySwingSound instead of the anisnd/sounds.ini based stuff.

**Comment by skellytz** [comment]
I'd use animation soundsets (2DA/INI) with SHOOT, ATTACK_SLASH, ATTACK_BACKSLASH and ATTACK_JAB instead of item-sound links for monster attacks.

For example, the wyvern has three attack animations:
slash --> beak --> wyver05.wav
backslash --> claw --> wyver07.wav
jab --> tail (poison) --> wyver06.wav

The corrected 2DA soundset table:
ATTACK    			***
ATTACK          			0
(...)
DAMAGE          		wyver08
DAMAGE          		0
DIE             			wyver09
DIE             			0
(...)
ATTACK_SLASH    		wyver05
ATTACK_SLASH    		2
ATTACK_BACKSLASH	wyver07
ATTACK_BACKSLASH	2
ATTACK_JAB      		wyver06
ATTACK_JAB      		2
(...)
BATTLE_CRY			wyver03 wyver04
BATTLE_CRY			0 0
SELECTION                       wyver01 wyver02
SELECTION                      0 0

Make sure the monster weapon items have proper swing percentages (overhand/slash, backhand/backslash, thrust/jab) corresponding with the attack cycles and sounds.

**Comment by lynxlynxlynx** [comment]
I considered overriding these, since I doubt many mods touch them, but itm files are a whole other thing. This would be viable if the fixpack took care of the data, but if we have to do it, it would break mods that modify it.

**Comment by skellytz** [comment]
Soundsets are generally messed up in every BG game variant and fixing anything would needlessly take you the same amount of time and effort I went through. Infinity Sounds will address most of such issues at the end of the mod chain for compatibility. I already have a few thousand lines of code correcting, restoring, matching and synchronizing sounds. I guess you could wait for the upcoming releases of Infinity Animations and Infinity Sounds before deciding on the best approach.

**Comment by lynxlynxlynx** [comment]
We already softly require the fixpack, since it avoids so many dialog and scripting data bugs. It's unfortunate that the fixpack part of IS isn't going into it. The mod looks great, but it's also a tweakpack, so we can't really say it's mandatory.

We generally don't fix data bugs, since mods can and do, but this bug is about yet another mechanism for attack sounds. Not much work to implement and if anyone wants the perfect experience, IS is still available.

**Comment by lynxlynxlynx** [comment]
Hey @skellytz, did you release Infinity Sounds somewhere? I only see a partial inclusion in IA, but that's it. Couldn't find it on SHS besides the thread nor on Github.

**Comment by skellytz** [comment]
No, not yet. Very soon, though!

**Comment by lynxlynxlynx** [comment]
Do you have a repo somewhere I could take a look at?

**Comment by skellytz** [comment]
I still need to create it. I'll let you know when it's ready. Thank you for reminding me!

**Comment by lynxlynxlynx** [comment]
Ah, too bad. I checked and the items have swing chances set nicely, so what's left for GemRB is just creating&shipping the fixed versions of the handful problematic soundset tables. Which I'm sure you already have laying around. :)

**Comment by skellytz** [comment]
OK, if you want my help, first I need to know which of these issues GemRB has already addressed:

**1. CRE soundset ATTACK2, ATTACK3 and ATTACK4 don't play**

Creatures have four attack sound slots in the CRE soundset:

* ATTACK1 (0xdc)
* ATTACK2 (0xe0)
* ATTACK3 (0xe4)
* ATTACK4 (0xe8)

Only ATTACK1 plays its sound, the other attack soundset slots don't work. For example, in BG2 wolf.cre:

* ATTACK1 -> StrRef: 5558 (wolff05.wav) always plays on every attack
* ATTACK2 -> StrRef: 5559 (wolff06.wav) never plays on any attack

All four ATTACK soundset slots should be enabled.

Most creatures have separate audio files for different attack animations (slash, backslash, jab). These sounds were designed to be played on specific attack animations. Back to the wolf example:

* wolff05.wav matches only the slash attack animation cycle (the wolf bites with its fangs)
* wolff06.wav matches only the backslash attack animation cycle (the wolf leaps with its paws and bites)

The attack sounds should be matched with the attack animations:

* ATTACK1 should play only on the SLASH attack animation cycle
* ATTACK2 should play only on the BACKSLASH attack animation cycle
* ATTACK3 should play only on the JAB attack animation cycle
* ATTACK4 should play only on the SHOOT attack animation cycle

If these ATTACK sounds simply played at random on any attack, there would be lots of mismatches between the attack sounds and the attack animations.

**2. 2DA sounds overlap with CRE sounds**

* 2DA.DAMAGE overlaps with CRE.DAMAGE (0xec)
* 2DA.DIE overlaps with CRE.DYING (0xf0)
* 2DA.ATTACK_SLASH overlaps with CRE.ATTACK (0xdc)
* 2DA.ATTACK_BACKSLASH overlaps with CRE.ATTACK (0xdc)
* 2DA.ATTACK_JAB overlaps with CRE.ATTACK (0xdc)

These sounds play at the same time. For example, BG2 wolf:

* dwolf08.wav in MWLF.2DA.DAMAGE plays at the same time as wolff08.wav in WOLF.CRE.DAMAGE when the creature gets damaged
* dwolf09.wav in MWLF.2DA.DIE plays at the same time as wolff09.wav in WOLF.CRE.DYING when the creature dies
* dwolf05.wav in MWLF.2DA.ATTACK_SLASH plays at the same time as wolff05.wav in WOLF.CRE.ATTACK when the creature attacks with the slash animation
* dwolf06.wav in MWLF.2DA.ATTACK_BACKSLASH plays at the same time as wolff05.wav in WOLF.CRE.ATTACK when the creature attacks with the backslash animation
* dwolf06.wav in MWLF.2DA.ATTACK_JAB plays at the same time as wolff05.wav in WOLF.CRE.ATTACK when the creature attacks with the jab animation

2DA sounds should be disabled if a given creature has sounds in the corresponding CRE soundet:

* 2DA.DAMAGE shouldn't play if a creature has CRE.DAMAGE sound
* 2DA.DIE shouldn't play if a creature has CRE.DYING sound
* 2DA.ATTACK_SLASH shouldn't play if a creature has CRE.ATTACK1 sound
* 2DA.ATTACK_BACKSLASH shouldn't play if a creature has CRE.ATTACK2 sound
* 2DA.ATTACK_JAB shouldn't play if a creature has CRE.ATTACK3 sound
* 2DA.SHOOT shouldn't play if a creature has CRE.ATTACK4 sound

The engine already properly disables:

* 2DA.SELECTION if a creature has CRE.SELECT_COMMON
* 2DA.BATTLE_CRY if a creature has CRE.BATTLE_CRY

All this will allow for creatures with the same animation to have completely different soundsets.

**3. Hardcoded ITM weapon sounds overlap with 2DA and/or CRE attack sounds**

The following weapon items are hardcoded to play sounds on attacks:

* ANGHEG1.itm -> ANKHG06.wav
* ANGHEG2.itm -> ANKHG05.wav
* BASIL1.itm -> BASIL06.wav
* BASIL2.itm -> BASIL05.wav
* BASILG1.itm -> GBASI05.wav
* BASILG2.itm -> GBASI06.wav
* BASILG3.itm -> GBASI07.wav
* ETTERC1.itm -> ETTER05.wav
* ETTERC2.itm -> ETTER06.wav
* WYVERN1.itm -> WYVER05.wav
* WYVERN2.itm -> WYVER06.wav
* WOLFWI1.itm -> WWOLF07.wav
* WOLFWI2.itm -> WWOLF06.wav

These hardcoded item sounds overlap with any attack sounds in the 2DA or CRE soundsets (they play at the same time). The hardcoded weapon item sounds should be disabled. They are leftovers from the legacy BG1 engine which didn't allow for setting different sounds for melee and ranged attacks.

**Comment by lynxlynxlynx** [comment]
Thanks, I was mostly curious about the fixed animation files (point 3), but a more thorough look is also helpful.

1. We already use ATTACK2-4, although in a bit of a roundabout way.
1.1. Btw, is the difference between war cries and attacks that the first one is used just on the first attack?
2. It appears we currently give precedence to the 2da.
3. Since we don't have the exception code, we just need the fixed animation files. The TobExAL stuff shouldn't be needed. I'll look at the repo you pushed.

**Comment by skellytz** [comment]
>     1. We already use ATTACK2-4, although in a bit of a roundabout way.
>        1.1. Btw, is the difference between war cries and attacks that the first one is used just on the first attack?
War cries (or battle cries) should play whenever the creature sees and acquires a target, ie before it even moves to attack the target. Battle cries shouldn't play on attack animations at all. That was messed up in BG2 because the battle cry sounds were mistakenly placed in 2DA general attack sound slots for almost every monster.

>     2. It appears we currently give precedence to the 2da.
Are you sure? This is a problem because many creatures use the same existing animations but have different soundsets. Examples: A skeleton warrior has a different soundset than a regular skeleton, but both use the skeleton animation. A succubus has a different soundset than a sirine, but both use the sirine animation. CRE soundset should override the 2DA in the following cases (assuming you've matched CRE attack sound slots with attack animations):
* 2DA.DAMAGE shouldn't play if a creature has CRE.DAMAGE sound
* 2DA.DIE shouldn't play if a creature has CRE.DYING sound
* 2DA.ATTACK_SLASH shouldn't play if a creature has CRE.ATTACK1 sound
* 2DA.ATTACK_BACKSLASH shouldn't play if a creature has CRE.ATTACK2 sound
* 2DA.ATTACK_JAB shouldn't play if a creature has CRE.ATTACK3 sound
* 2DA.SHOOT shouldn't play if a creature has CRE.ATTACK4 sound
* 2DA.SELECTION shouldn't play if a creature has CRE.SELECT_COMMON
* 2DA.BATTLE_CRY shouldn't play if a creature has CRE.BATTLE_CRY

>     3. Since we don't have the exception code, we just need the fixed animation files. The TobExAL stuff shouldn't be needed. I'll look at the repo you pushed.
I need a bit more time with this version of IS, so the repo isn't ready yet.

I'd consider several more engine fixes. Of course, Insomniator should be contacted for more details. Here's the list of the TobEx fixes that most of my soundset changes rely on:
* TobEx Core [Sound] Animation Sound Fix=1
Fixes a bug that prevented the sounds in the middle of animation soundset 2DA files from playing.
* TobEx Core [Sound] Existence Sound Fix=1
* Fixes a bug where PICKED_POCKET sounds were played when EXISTANCE sounds were called for in the creature soundset. This was corrected to EXISTANCE5.
* TobEx AfterLife Core [Sound] Sequence Sound Override Fix=1
Without it many animations will be crippled. For example, SHOOT attack animation and sound won't work at all for many animations because they are hardcoded with SHOOT -> READY animation override. Ankheg is a good example.
* TobEx AfterLife Core [Sound] Externalise Animation Sound Reference Override=1
Without it some animations won't have working 2DA soundsets. Here's are the overrides I've created for IS:
0x7101 MBAS2 BASILISK_GREATER
0x7200 MBER4 BEAR_BLACK
0x7202 MBER3 BEAR_CAVE
0x7203 MBER2 BEAR_POLAR
0x7401 MDOG2 DOG_WAR
0x7501 MDOP2 DOPPLEGANGER_GREATER
0x7701 MGHL3 GHOUL_REVENANT
0x7702 MGHL2 GHOUL_GHAST
0x7B01 MWLF5 WOLF_WORG
0x7B02 MWLF6 WOLF_DIRE
0xA000 MWYV2 WYVERN
0xE060 MLCH  LICH_WHITE
0xE070 MMTA  MINOTAUR
0xE090 MMAR  MARILITH
0xE0B0 MTRL  TROLL_BLUE
* TobEx Tweak | Sound:Enable Animation Attack Sounds=1
Enables the use of SLASH, BACKSLASH, and JAB sounds in animation soundset 2DA files. These sounds play when the appropriate attack animation is played.
* TobEx AfterLife Tweak | Sound:Disable Hardcoded BG1 Item Sounds=1
To disable the sounds mentioned in pt 3 [here](https://github.com/gemrb/gemrb/issues/374#issuecomment-1662576475).
* TobEx AfterLife Tweak | Sound:Creature Embedded Sound overrides 2DA Entry=1
So that CRE sounds have priority over 2DA sounds for the reasons mentioned above.
* TobEx AfterLife Tweak | Sound:Restore Creature Attack Sounds 1=1
To enable ATTACK2-4 in CRE soundsets (ATTACK1 – on slash animation, ATTACK2 – on backslash animation, ATTACK3 – on jab animation, ATTACK4 – on shoot/range animation)
* TobEx AfterLife Tweak | Sound:Restore Creature Attack Sounds 2=1
Without it, if a creature uses a weapon eg a sword which uses the hardcoded "swing" sounds (SWI_*.wav) the CRE attack sounds won't play.

**Comment by lynxlynxlynx** [comment]
Ok, so I started working on this holistically, checking how things work currently and how they should. 

A question:
- 2DA.ATTACK: you haven't mentioned this — what is it used for? It's effectively the 5th slot in your scheme
  - an older comment says: 2da attack was played only if the weapon was of type misc (so no swing sound), which would make sense

**Comment by skellytz** [comment]
> an older comment says: 2da attack was played only if the weapon was of type misc (so no swing sound), which would make sense

That's how CRE.ATTACK originally worked. The hardcoded item sound code conflicted with the attack sound playback routine, but nobody really noticed at the time because BG1 NPCs (usually humanoid) who wield standard weapons don't really have sounds in CRE.ATTACK. We don't know what the original intention was, but TobExAL gives an option for both weapon-type (SWI_) and CRE.ATTACK sounds to play at the same time and that's my preference, too. The rationale behind it is that if you give a cat a sword and tell it to swing it with full force, the cat will meow while exhaling, but the sword will also produce a regular swoosh. In other words: the cat's meow shouldn't disable the rules of aerodynamics. (Please don't start a debate on cats being creatures with cosmic powers; it was just an example.)

In BG2, 2DA.ATTACK plays regardless of what weapon a creature uses, on every type of attack animations, and on top of CRE.ATTACK. After TobEx restored 2DA.SLASH, 2DA.BACKSLASH, and 2DA.JAB it now plays on top of these as well. So, basically it's supposed to be a slot that plays sounds on every melee attack for an extra flavor. Or, if your creature has only one attack animation, you could use this slot and blank slash, backslash and jab. One or two modders who know how soundsets work could find a creative use for it; otherwise, it isn't very useful for the available vanilla creature sounds that usually need to be matched with specific attack animation cycles.

While it wasn't my suggestion, after my reports on this slot being occupied by sounds reserved for battle cries (and other people's complaints on how ogrillons yelled "you mess with me..." on every attack) Beamdog devs decided to disable the equivalent INI.ATTACK slot altogether. It simply doesn't work in EE games anymore. That was the most effortless solution for them. Infinity Sounds also doesn't use this slot (and removes sounds from it) for consistency.

**Comment by lynxlynxlynx** [comment]
Ok, tens of commits later we're in a much better state. I fixed a bunch of bugs related to the different verbal constant layouts, checked everything you talked about here and finally added the eponymous stuff. I've also added IS to the recommended install list. Thanks! 

We still have a bunch of unknowns for the ini-based counterparts, which is partly related to #175 and #92 , partly ignorance, but that's for separate issues.
