### ISSUE TITLE
[bug] promenade entrance battle has sound issues?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#376]
When you exit the cutscene battle starts. Are the attack shouts supposed to be heard? Some of the actors cut each other off, since there's only one channel, so eg. the cowled lines aren't all heard.

Easiest to compare with a video.

**Comment by lynxlynxlynx** [comment]
@caillean7 can you "look" at this one? I'm pretty sure the cutting off of speech shouldn't happen, but is there any other sound difference, like perhaps the battle cries? Seemed a bit crowded when I played it.

If you don't have a save before exiting, you can just mta to the area and ctrl-j to the exit. BTW, iesdp has all area codes listed: https://gibberlings3.github.io/iesdp/appendices/index.htm

**Comment by caillean7** [comment]
The battlecries cut off the speech, eg. "You dare to attack me here..." is cut off, "You will suffer..." isn't played at all. I kinda think that wasn't this way always - how about #208? I'll try testing with code prior to that.

Also, the battlecries are more numerous and seem to "echo" each other - but this is old news, isn't it - I just can't seem to find the issue in question...

I uploaded videos [here](https://www.magentacloud.de/share/7.qo.qgovx) because I don't have any accounts on video sites like YT.

**Comment by caillean7** [comment]
Nah, that fix for #208 didn't make a difference.

Also, another thing I noticed - there's the night / day video played by GemRB when you exit the to the promenade, IE doesn't do that. It's the same save I used.

**Comment by lynxlynxlynx** [comment]
Hmm, for that last thing, please check if the cutscenes involved do any DayNight or AdvanceTime actions.

Repeating attacks were there also in the original, but perhaps they only vocalized the first one? I sure hope not.

**Comment by caillean7** [comment]
> check if the cutscenes involved do any DayNight or AdvanceTime actions.


Indeed, they made sure this cutscene runs in daylight, CUT01.BCS contains:

`DayNight(DAWN_END)`


Remember the Mazzy-Altar-thing? I wonder if it's supposed to play the day / night video there when the area is switched from shaded to restored - if I remember correctly, GemRB does play it.

**Comment by caillean7** [comment]
> perhaps they only vocalized the first one?

Do you mean in general or in cutscenes? Because, I just did a couple of quick tests here, on IE, having my PC getting attacked by people and healing him with Ctrl+R, and those enemies did voice their battle cries only with the first attack, then they happily hacked and slashed at me in silence. So I wonder if this is a general thing on the original?! I guess we all kinda have blinders on with such things because we probably played only on GemRB for years.

**Comment by lynxlynxlynx** [comment]
DayNight fixed, shouldn't happen again.

Casting sounds don't use the speech channel, so only the verbal constants can interfere. They are very loud in your video though, do you have the same audio settings in gem-baldur.ini and baldur.ini? It has only 5% less volume in sndchann.2da than what we use for overhead text sounds.

I don't see any difference in the attack sounds though, there's just several thieves. In general it depends on the scripting actions involved.

**Comment by caillean7** [comment]
I figured I must have different audio settings because of the loudness, but no, they're both the same. I think casting sounds should be effects? Both at 100. The only difference is, I use Environmental Audio option in GemRB, while I can't activate it with wine. Btw., I notice that Environmental Audio effects also GUI related sounds, is that intended?

**Comment by lynxlynxlynx** [comment]
One thing you can try is modding sndchann.2da and just playing around in a save with a mage. Eg. if you set casting to 0, do both the casting and completion sounds stop working? There's a tiny chance one would be from actions and thus lower. What we use for overhead text is all at 100 (charN, monster, dialog), so not really important what the details are (and it's clearly loud).

**Comment by caillean7** [comment]
> Eg. if you set casting to 0, do both the casting and completion sounds stop working?

No, only the casting sound (incantation), the completion sound (effect) gets still played. I see actions are at 65, which should be even quieter - but do you or others have this issue, too, then? Or is this an oddity with my system perhaps? Because, if it is, it's no big deal. Normally I would've just turned it down, but I remember turning effects up to 100 when I tested the thing with sound effects coming from corpses cygarniczka reported a while ago, so that I could hear better. That's the only reason for the being so loud.

**Comment by lynxlynxlynx** [comment]
This second part is important — we use the same channel for both. Try disabling some of the others to find out which one dictates the completion sound.

**Comment by caillean7** [comment]
It's MISSILE.

**Comment by lynxlynxlynx** [comment]
Just brilliant, but at least it's quieter. Thanks. :)

**Comment by lynxlynxlynx** [comment]
With that out of the way, the speech channel thing is the only obvious remnant and since it's tracked separately, closing.
