### ISSUE TITLE
[subviews] guiinv is drawn over the action win

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#390]
iwd2 guiinv is drawn over the action win with an odd black gap the only visibly problematic part:
![image](https://user-images.githubusercontent.com/121515/68870138-b070e200-06fa-11ea-8f2a-daf8fe95b81f.png)

Both still work fine.

**Comment by bradallred** [comment]
what resolution?

**Comment by lynxlynxlynx** [comment]
default of 800x600.

**Comment by bradallred** [comment]
I think this is due to the bizarre CHU TextEdit discovered in #222. It makes GUIINV extra tall and in d44a820 I didn't bother getting an exact measurement to resize it. I'm guessing this is only in SDL1.2, however, since in @MarcelHB's screenshot you can see that window has an alpha. I don't think an alpha allows events to passthough on windows tho (maybe?). 

If you add the alpha flag to the window does that fix the display issue and can you still click the buttons on the top area that are currently covered?

**Comment by lynxlynxlynx** [comment]
WF_BORDERLESS had no effect, so I just cut if properly.

**Comment by bradallred** [comment]
yeah, `WF_BORDERLESS` just disables those decorative borders that aren't even part of the window. `WF_ALPHA` should have fixed it, but I don't like using that for square windows since it unnecessarily impacts performance on SDL 1 due to forcing an alpha blend.

what you did is the best solution.
