### ISSUE TITLE
Item range is also limited by visual range -> get rid of VOODOO_WPN_RANGE*

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#413]
In #98 we found out that ranged weapons ignore whatever is set for their range in the item. But no other than The Imp himself had a helpful comment (yes, you read that right!) recently, hinting that perhaps, just like spells, they're limited by visual range.

Meaning this wouldn't crop up with long range stuff, so testing by tweaking darts and even melee weapons is the way to go. In retrospect I'm not sure Gesen was tried with range 10 in that report.

If true, we can get rid of VOODOO_WPN_RANGE constants too. :)
... THE ANSWER IS YES.  Launcher aren't affected, since it's their ammo that has the range. IOW any item of Ranged type is affected.

**Comment by caillean7** [comment]
I'm afraid I'm being daft again, but I'm not sure if I'm getting this right: You're in doubt if the reducing range actually does nothing, in other words, reducing the range in NI might have an effect after all? Just enhancing weapon range will likely be pointless because the range might be capped by visual range?

**Comment by caillean7** [comment]
That thought about visual range sounded kinda plausible to me, since we know it's the same e. g. with the fireballs, so I did a few quick tests: doubling the range of the simple dart does indeed increase its range in game. I set it to 40, measured ~430 px. The range of the long bow was 430 px, too, just like cygarniczka measured, increasing it made no difference. So 430 px seems to be the maximum range in IE which does correspond with the visual range, if I'm not mistaken. I had 422,6 px for the fireball range, but this case here is easier to measure exactly, I'd say (from the center of one footcircle to another). So yeah, I don't know if you need more extensive testing done, but this looks like the Imp's idea has some merrit (and c'mon, he's an institution of his own, been around forever and doing... well, his thing).

**Comment by lynxlynxlynx** [comment]
That's just half the proof though, what happens if you set a bow to range 14 for example?

**Comment by caillean7** [comment]
> That's just half the proof though, what happens if you set a bow to range 14 for example?

Huh, nothing, the same goes for short bows, which have the same range as long bows, they always seem to have a range of 430 px. They are type 'Launcher', while darts and throwing daggers have type 'Ranged'. For darts and throwing daggers reducing and increasing works (up to the cap at 430 px). So I guess the range for Launcher types can't be altered - or it has no effect in game - while it's possible for Ranged types. The max. range for both types still is 430 px.

**Comment by lynxlynxlynx** [comment]
Interesting! Do arrows have a range set? Launchers are always tricky, since two items are involved.

**Comment by caillean7** [comment]
Indeed, their range is set to 100 ft. Reducing it to 10 works, Minsc walked really close up to poor Imoen before shooting at her. I also tried setting to 200, which had no effect again. Measured 430 px exactly.

**Comment by caillean7** [comment]
Range adjustment works for certain ammo items, not for others. Not even arrows are consistent. It does for e.g. the standard arrow, and Arrows +1, but not for Fire Arrows. It's madness. Don't reproduce that with GemRB, will you?

**Comment by lynxlynxlynx** [comment]
What's different about fire arrows? oO I will just believe you made a mistake in your testing, missing a step.

Actually using the range and just capping it is pretty sane.

**Comment by caillean7** [comment]
> I will just believe you made a mistake in your testing

:astonished: Well, always a possibility, but: :stuck_out_tongue: 

At least the bullets work different than arrows, I re-checked that 3 times. Also, normally all this makes no difference at all while playing. All the ammo items I looked at had their range set to 100, which is far more than the cap anyway.

**Comment by lynxlynxlynx** [comment]
How are bullets different?

**Comment by caillean7** [comment]
Their range can't be reduced like most of the arrows - well, I tested 3 of 6 different types. They have different launchers, and obviously stuff like (un)unsable flags, and they list different projectile types (not sure if that means anything in this context).

**Comment by caillean7** [comment]
So are you contented with an answer to your initial question, or do you want to investigate this ammo thing further? My usual chaotic self being tired yesterday might as well messed up with the Flame Arrows, so I could sample some more arrows and bolt items if you deem it necessary.

**Comment by lynxlynxlynx** [comment]
I have all I need for the basic case that covers 98% of uses. The rest is less clear, but can probably be ignored; either way, I need to look into it myself too, check the code, before I'd potentially have further questions.

**Comment by caillean7** [comment]
I was curious if Blindness would affect ranged weapons, so I just tried it. It does affect bow / arrows, slings / bullets and crossbows / bolts all the same, shooting with a blindness effect will make the shooter approach the target and shoot point blank. (Not sure if it's even helpful, but there it is - another mosaic piece of knowledge about the enigma that is the Infinity Engine.)
