### ISSUE TITLE
Do stunning blow and quivering palm really work only on level 6 or less actors?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#460]
Old note from the wiki:

> These monk features have level limits in the data (spell effects). It seems a bit absurd that they would really work only on creatures with HD 6 or less, especially the quivering palm, as you get it late.

Is any of that (still) true? Can you palm a level 10 thing in bg2? If so, does it also work in gemrb?

**Comment by caillean7** [comment]
On IE these abilities work also on higher level critters. I could stun e. g. the Shade Lord, which is level 20 with Stunning Blow. Quivering Palm seems to work, too, though those high level targets probably have good saving throws and I never actually succeeded in killing one - at least they had to make a save.

On GemRB Stunning Blow works as well, tried several higher level creatures. About Quivering Palm it's a little hard to tell. GemRB doesn't display if someone has to make a save, it seems, even if all options in 'Feedback' are selected. Again, like on IE, having a hard time really slaying something, because of good saves.

**Comment by lynxlynxlynx** [comment]
Thanks!
