### ISSUE TITLE
[bug] PST: Menu windows not centered in high resolutions

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#463]
**Description**
When using widescreen mod on PST, it displays the menu / inventory / etc. windows in the top left corner on the screen, unlike the other games which center those windows. Reported [here](https://www.gibberlings3.net/forums/topic/30878-resolution-problem-on-raspberry-pi-3/). I tried it, too, looks odd.

**GemRB version**
0.8.6-git

**Expected behavior**
Center all menu windows on PST as well.

**Comment by lynxlynxlynx** [comment]
I think this is now automatic in subviews, but I have a memory of also @chilvence writing a patch for this a few years back.

**Comment by MarcelHB** [comment]
This is not a matter of GemRB? If I start the original game, it's also positioned there. Because the mod simply leave the MOS file and controls right there.

**Comment by caillean7** [comment]
Not sure how it looks in subviews (won't compile). So even if it's widescreen mod causing this, it could still be changed on GemRBs side?

**Comment by chilvence** [comment]
I don't actually remember submitting a patch for this, but I do remember trying to work out a good solution. I was also playing with the widescreen patch, but I think I might have tweaked my GUIscript files to center the windows, I wouldn't call it a patch, because on reflection, the problem was much more complicated. There is a lot you can do by cleverly overriding the .CHU interface files, but at some point, you also need to provide extra graphics to fix the fact that the game was targeting a 640x480 CRT monitor...

**Comment by chilvence** [comment]
That said though, the original inventory and character windows etc do pretty much look ok with a simple re-centering, the tricky one is the main world interface

**Comment by bradallred** [comment]
this is indeed already handled in the subviews branch. You currently need SDL 2 to compile it.

**Comment by lynxlynxlynx** [comment]
With at least three workarounds, it's pointless to spend more time on this.
