### ISSUE TITLE
Recheck badspells reports

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#465]
We have old testing data on the wiki that hasn't been migrated yet:
http://www.gemrb.org/wiki/doku.php?id=developers:bugs:badspells

All the reports should be checked if they're still relevant and if the original had the same problem. Anything that is really a GemRB bug should get an individual report.

@caillean7 can you perhaps take a look?

**Comment by caillean7** [comment]
Sure, sign me up.

**Comment by caillean7** [comment]
> - detect evil sometimes shows the output several times for the same actors [noticed with summons]

Looks fine; tested multiple times on mobs consisting of summons and enemies both.

To be continued...

**Comment by caillean7** [comment]
> check if wizard eye really forwards gaze attacks (did it in the original?)

I tried that with a beholder because - gaze attack. First, the beholder ignores the wizard eye - it has an invisibility ring equipped, I thought beholders have true sight, but it wasn't bothered by the eye. So I removed the ring. Now the bolder attacks the eye, though not with gaze attack, just physical attacks. As soon as any party member comes in sight, it will ignore the eye and go for the party - with gaze attacks, but no gaze attacks on the eye. Not ever. So unless there's another test that could be done, it seems there's nothing to it - fun as it was to test tho.

**Comment by lynxlynxlynx** [comment]
There were basilisks in bg1, but I don't know if this spell was available. Probably it's just a missing feature and the description comes from the rulebook.

**Comment by caillean7** [comment]
Also, the eye is usually invisible, the beholder ignores it, and I guess basilisks as well (trying to create one with the console crashes BG2).

**Comment by caillean7** [comment]
I've checked all items on the list now, and all relevant issues are referenced here. The list above has some info about the points I wasn't able to verify.

**Comment by lynxlynxlynx** [comment]
Thanks, one page less to migrate!
