### ISSUE TITLE
Do spellhaunts (nishruus and haekeshars) drain too much?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#469]
They're the mage banes, draining spells. Spellhaunts in particular can be found in Watcher's Keep (level 1?) and currently also drains potions and other quick items - is that as expected, same in the original?

**Comment by lynxlynxlynx** [comment]
@caillean7 Something simple for a change. Is it true their attacks should also drain potions, scrolls, wands ... besides just spells?

**Comment by caillean7** [comment]
According to lots of websites, they should and did at some point - mostly really old stuff. However, I couldn't verify that. Stocked up a couple of mages with all sorts of magical equipment / scrolls / potions and consoled 3 nishruus and 3 hakeashars and had them attacked for almost 10 minutes a few times. No items drained, not even charges from wands of items like the Ring of Energy / Ring of the Ram.

I uninstalled the fixpack, too, just in case. There's something interesting in the readme of the Fixpack, though:

> Dropped the Nishruus and Hakeashars Eating Non-Magical Items fix. In Throne of Bhaal, the opcodes responsible for this bug have been disabled with the official patch. In Shadows of Amn, the bug is unfixable

Could it be that ToB removed the whole item draining thing because it was glitchy? ToB's readme doesn't mention anything, though. I could make a SoA only install?

**Comment by lynxlynxlynx** [comment]
We don't care about SoA — we decided a long while ago that the few differences are not worth losing hair over. Especially since it's hard to get it nowadays.

So you're saying they've only drained the spellbook, right?

**Comment by caillean7** [comment]
Yep, memorized arcane spells only. The beamdog forums don't seem to have any complaints about thieving nishruus and hakeashars either. I'll test on EE, too, to be on the safe side.

**Comment by lynxlynxlynx** [comment]
No need, thanks!
