### ISSUE TITLE
[bug] BG2 'Badspells' - Magic Missile too fast

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#479]
See #465 

**Description**
Magic Missiles 'fly' too fast on GemRB, almost 3x faster than on IE. Recorded it, played videos in slow motion, stopped time, result was ~5.67s for GemRB, 16.16s for IE. Clips are included in the attached zip, if you want to see them.
[M_Missile.zip](https://github.com/gemrb/gemrb/files/3944991/M_Missile.zip)

**Comment by lynxlynxlynx** [comment]
Interesting, since the speed is set in the projectile, which came with the game — magicmis.pro. So it's probably an overall projectile speed problem, just like with actor movement.

**Comment by caillean7** [comment]
I'll check some other spells to see if it's a more general thing - any preferences which ones to pick?

**Comment by lynxlynxlynx** [comment]
Not really. For example fireball has the same speed, holy/unholy word probably too, many sparks (think bless or haste), but it's the factor that we're after anyway, so what you measure doesn't matter, just that it's from both engines.

**Comment by caillean7** [comment]
I tested 3 more my mage had memorized (Fireball, Melf's Acid Arrow, Spook), and they're roughly the same on both engines, deviations of a few ms probably due to my no good reactions. So looks like Magic Missile be somewhat special after all...

**Comment by lynxlynxlynx** [comment]
I guess that's both good and bad news. Projectile::CreateIteration is only used for MM, since it's cloning behaviour is hardcoded and we could scale the Speed there.

Does it work to reduce the speed in magicmis.pro? Some of the projectile speeds are 750, 1000 and it just makes me wonder if that was a cheap attempt at trying to make them instant or what. There's a very slight chance the speed is constant for all projectiles too.

**Comment by caillean7** [comment]
I changed the speed from 40 to 400 - no difference.

**Comment by lynxlynxlynx** [comment]
Try something like 10 or 5, since slower would be much more noticeable than faster. And it avoids any hardcoded caps like with visual range.

**Comment by caillean7** [comment]
Oh hell, I kinda forgot to click on save when I altered the projectile earlier. Sorry. But, it works both ways, you can make it faster and slower.

**Comment by lynxlynxlynx** [comment]
Heh, it also seems from the video we have a math bug somewhere — one of the clones veers off significantly. Not that noticeable, since it's fast.

**Comment by bradallred** [comment]
I have no idea what the math behind it is, but couldn't just moving faster be the cause of that?

**Comment by lynxlynxlynx** [comment]
I can't imagine how and all the clones get the same speed. My first guess would be bad handling of the 0/360 angle border.

**Comment by lynxlynxlynx** [comment]
One other researcher believes the speed is used as "horizontal" pixels per tick, which is clearly different from what we do in DoStep. Worth a try.

**Comment by lynxlynxlynx** [comment]
Ok, so there's actually two projectiles. The spell references the hardcoded one we provide, while iterating down, we also spawn the game provided projectile for the last missile:
```
[PRO/DEBUG]: Speed: 30, bend: 0, type: 71, name: SPMAGMIS | PARENT                                                                                  
[PRO/DEBUG]: Speed: 30, bend: 0, type: 70, name: SPMAGMIS                                                                                           
[PRO/DEBUG]: Speed: 30, bend: 1, type: 69, name: SPMAGMIS                                                                                           
[PRO/DEBUG]: Speed: 30, bend: 2, type: 68, name: SPMAGMIS                                                                                           
[ResourceManager]: Found 'MAGICMIS.pro' in 'chitin.key'.                                                                                            
[PRO/DEBUG]: Speed: 40, bend: 3, type: 67, name: MAGICMIS  
```
It's this last one that has a higher speed set and it this one that has a wonky path. I looked into it since if you slow things down, there's then three outliers. It's an ids entry problem, but fixing that also flamestrikes the target. :D It's from the way we do the iteration ...

As for the speed itself, I didn't measure anything, but 3/4 lower looks good.
