### ISSUE TITLE
[feature] iwd2: summons have improper action bars

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#492]
The table for non-pc action bar is missing (qslot2.2da), so some summons get a bad one. Figure out which and if the table approach (like in bg2) is the way to go.

First step is to try all the summoning spells, several times if needed (since they can produce different creatures) and see which have action bar problems.

**Comment by lynxlynxlynx** [comment]
@caillean7 Another simple one. I think it's easiest to test by starting with one of the parties with a sorcerer and just cheating in more xp to get all the spells.

**Comment by caillean7** [comment]
I've been through pretty much all summons (except some spells give leveled ones, didn't try all caster levels). Every single summon has the same action bar, or rather none, since the IE basically displays the same bar like when you have the whole party selected. You don't have direct control over the summons' special abilities / spells. Some, like elementals ((Lesser) Planar Binding) or (Caco)Fiend don't have bars at all, since you can't select them, they are not under caster control. By default it looks like this:

![iwd2_actionbar](https://user-images.githubusercontent.com/54738589/71127019-7eb3d500-21ea-11ea-920c-719d48396f90.jpg)

If you have manipulated the formation buttons, it also shows in the bar of the summons, like shown with the scrag, which is selected, in this screenshot:

![iwd2_actionbar2](https://user-images.githubusercontent.com/54738589/71127159-ccc8d880-21ea-11ea-856a-e405f77697c7.jpg)

I sampled some on GemRB, they all have full length bars like party members, with a seemingly random selection of abilities, so you even can use e. g. tracking abilities for some. Basically, they're all wrong. It's probably unnecessary to add any 2da tables here, if you can just assign the 'whole party selected' view to summoned creatures.
