### ISSUE TITLE
[subviews] Some games return to broken main menu

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#556]
**Describe the bug**

When clicking something in the main menus of IWD, IWD2, BG2 and PST, there are Python errors. For IWD/IWD2 this is especially bad since the main menu buttons are gone then.

IWD2 (other games look similar):
```python
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\gemrb\GUIScripts\iwd2\Start.py", line 62, in OnLoad
[Python/ERROR]:     VersionLabel = StartWindow.CreateLabel(0x0fff0000, 0,0,800,30, "REALMS2", "", IE_FONT_SINGLE_LINE | IE_FONT_ALIGN_CENTER)
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUIClasses.py", line 174, in CreateLabel
[Python/ERROR]:     return self.CreateControl(control, IE_GUI_LABEL, args[0], args[1], args[2], args[3], args[4:])
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUIClasses.py", line 147, in CreateControl
[Python/ERROR]:     return self.CreateSubview(id, type, frame, *args)
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUIClasses.py", line 160, in CreateSubview
[Python/ERROR]:     created = self.AddSubview(view) # this will move the reference into the our window's group
[Python/ERROR]:   File ".\gemrb\GUIScripts\MetaClasses.py", line 44, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: RuntimeError: Cannot construct object with null ref.
```

**To Reproduce**
1. Start the game
2. Click on the load menu/options/...
3. Try to return, e.g. by pressing ESC or back-buttons.

**Screenshots**
![iwd2_main](https://user-images.githubusercontent.com/238558/71322993-9501af80-24ce-11ea-92f5-0585f66a54db.jpg)

**Comment by bradallred** [comment]
oh dear, what have I done :)

**Comment by bradallred** [comment]
on my quick first glance it looks like the start window is never getting closed... and then we try to create a new label with the same id as one that already exists.

I wonder how long that has been the case. it doesn't appear to even get close when we load a game which shouldn't be the case because we ought to be calling `DestroyAllWindows` when we start a game or quit a game.

so it looks like 2 issues:
1. `DestroyAllWindows` isn't being called when it should apparently
2. we need to either only create the labels if they don't already exist, or close the window so they are destroyed.

this used to work because we would just stomp over existing references, but that is no longer the case.

**Comment by MarcelHB** [comment]
Not for too long, I assume. At the time of reporting #403, I guess this error was not there.

**Comment by lynxlynxlynx** [comment]
I doubt 1. is a problem, since this sort of issue can be reproduced also once the game is loaded. #551 is a simple test case. The inventory creates labels for the weight text.

**Comment by bradallred** [comment]
@lynxlynxlynx that is exactly why 1 _is_ a problem. If the window were destroyed then you wouldn't be able to reproduce this that way because the control wouldn't already exist. I didn't do a deep dive debug, but i did put breakpoints in `~Window` and `~Control` and neither was called for this window/control afict, but others did ofc.

@MarcelHB I meant how long its been since the start window wasn't being closed. For all we know it has always been like this (or whenever `DestroyAllWindows` got broken). You wouldn't have been able to tell from #403 because that was from before things were changed to no longer stomp out existing entries.

**Comment by bradallred** [comment]
I see what is happening now. I added an optional parameter to `RemoveView` for deleting the control or just removing it from view. Something along this `CreateLabel` chain was not updated to reinsert the control into the view hierarchy. this is obvious when you realize the version label (the one causing this) is "missing" when you start the game. It being removed from the hierarchy is also the reason why my destructor breakpoints are never hit; it is stuck in limbo.

if you comment out the `view->RemoveFromSuperview();` in `GemRB_RemoveView` everything works again, but i'm sure that will break something else so the investigation continues.
