### ISSUE TITLE
Is building with Autotools a relic of the past?

### ISSUE THREAD

**Issue by kindaro** [gemrb/gemrb#669]
The [official building instructions][install] never mention anything but Cmake. In spite of that, there are `Makefile.am` files in the source tree. Are they of any use? As far as I am aware, Autotools use those files, not Cmake.

[install]: https://github.com/gemrb/gemrb/blob/master/INSTALL

**Comment by lynxlynxlynx** [comment]
A relic, yes. They were left there at the behest of packagers, but also portability in general. CMake has improved much since and time has passed, so perhaps it is available on enough obscure platforms by now.

We definitely don't maintain it, so there are likely some newer files missing from the targets. Which is as it should be, since we want to know if anyone wants to use them.

**Comment by kindaro** [comment]
I see, thanks.
