### ISSUE TITLE
gamecontrol tint/blend issue on tob startup

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#711]
Starting a new game, the starting viewport is lighter than everything else:
![image](https://user-images.githubusercontent.com/121515/80828607-dbd28500-8be5-11ea-95cf-413324e710fd.png)

**Comment by bradallred** [comment]
Is this just SDL 1? I didn't notice anything wrong when I just tried it.

**Comment by lynxlynxlynx** [comment]
Could be, I haven't tried on sdl2.

**Comment by bradallred** [comment]
this is interesting because it does not afflict SDL2 nor does it occur if you load the auto save. It makes me want to suspect the fade, but that is applied to the screen so it would move with the viewport instead of being stuck in place. I have no idea what blending effect we would be doing in game coordinates.

I suppose I should check master to be sure that SDL 2 even behaves as expected. Its starting to feel like this effect might just be completely broken for it.

**Comment by bradallred** [comment]
it works in f997361. would somebody that gets more than 7fps in the menus mind bisecting this further? :) 

the breakage shouldn't be much more recent than that, I had previously tried 6f9b2db and it was broken there.

**Comment by lynxlynxlynx** [comment]
Sure, will give it a spin.

**Comment by lynxlynxlynx** [comment]
It started with 662fe3da7.
Tip for bisecting on branches: just bisect skip any commits from main branch merges.

**Comment by bradallred** [comment]
yeah, bisecting wasn't my issue. its the several minute procedure for starting a new TOB with the awful SDL 1 performance I get.

Sadly, that commit breaking things actually points to a preexisting and previously buried problem. I'll dig in with the debugger later, but I suspect the fix may be non trivial, but hopefully not hair pulling either.

**Comment by lynxlynxlynx** [comment]
I forgot to mention, just reverting that on HEAD is enough, it's not a composite problem.

**Comment by bradallred** [comment]
yes, I'm aware that either reverting that or adding `BLIT_BLENDED` to the base terrain tile is enough to "fix" it. It is not the right fix tho; we shouldn't have to "blend" everything. 

The actual problem is the lazy/incomplete palette caching which is required for both SDL 2 and SDL 1 when we have a non-BAM sprite that needs no effects; doing an SDL_LowerBlit is much faster whenever we can get away with it.

**Comment by lynxlynxlynx** [comment]
Confirming the fix, thanks.
