### ISSUE TITLE
[subviews] inventory button borders flash

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#713]
Inventory item borders are flashing on mouse over (blue for magic, white as intended, all at once, but too fast). Only the green equipped border works fine, but I think that's an actual button state.

In other words:
- nothing or flickering on mouse over
- no blue border on magic items

**Comment by bradallred** [comment]
somehow broken by 9c56531. I'll look at it tomorrow.

**Comment by bradallred** [comment]
its not clear from your description if that fixed everything or not

**Comment by lynxlynxlynx** [comment]
It's much better, but the blue border appears only on mouse hover.

**Comment by bradallred** [comment]
The magic borders are there the entire time, they are just not visible due to a 0 alpha. I don't quite understand the intent with the code in master. We are using a color that has an alpha of 0 so I would expect the result that you get in subviews. Obviously in master the color is completely opaque, but that raises the question: why are we setting alpha to `0` if we want an opaque border? Also, I can't see how we the half transparent border effect since 0 produces an opaque result, but that isn't important.

I believe the fix is to set that borders alpha to 255. Does that sound right to you?

**Comment by lynxlynxlynx** [comment]
Sure. We don't have that white border flashing in master, so not sure what that's meant to solve — it's not present in the original either.

**Comment by bradallred** [comment]
That is not at all relevant to my question. I'm asking about the static blue borders that have an alpha value of `0` in master.

**Comment by lynxlynxlynx** [comment]
And I answered that with "sure".

**Comment by bradallred** [comment]
ok then :)

That is fixed AFIK. Anything else?

**Comment by lynxlynxlynx** [comment]
Yeah that fixed the flickering. Is the pulsating an intentional addition?
