### ISSUE TITLE
[subviews] can't close worldmap window with hotkey

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#754]
In master we close back down to he map window, but fully closing would work as well.

Making it a topwindow would fix also the problem that opening another topwindow doesn't close it.

**Comment by bradallred** [comment]
I didn't make it a `topwindow` at first because that would close the regular map window, but we can just call `OpenMapoWindow` in the close event. I also had thought we would run into hotkey issues, but then I realize that if its a `topwindow`  it will be closed and relinquish its global hot key so we can actually bind that to the "done" button.

In short, I think I'll follow that suggestion instead.

**Comment by bradallred** [comment]
I think that works nicely
