### ISSUE TITLE
Subviews & MSVC:  "Use of undefined type GemRB::GUIFactory"

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#766]
This error is really confusing me because I can't understand why it happens with Visual Studio and not GCC

The following files fail to build with the same error ```C2027, Use of undefined type GemRB::GUIFactory (Holder.h Line 76)```

```Animations,cpp, Calendar.cpp, AnimationFactory.cpp, Core.cppm ControlAnimation.cpp, DialogHandler.cpp, DisplayMessage.cpp```

```FAILED: gemrb/core/CMakeFiles/gemrb_core.dir/Animation.cpp.obj 
  B:\VS\VC\Tools\MSVC\14.26.28801\bin\HostX64\x64\cl.exe  /nologo /TP -DGEM_BUILD_DLL -DHAVE_CONFIG_H -Dgemrb_core_EXPORTS -I. -I..\..\..\gemrb\includes -I..\..\..\gemrb\core /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /Zi /O2 /Ob1 /DNDEBUG /showIncludes /Fogemrb\core\CMakeFiles\gemrb_core.dir\Animation.cpp.obj /Fdgemrb\core\CMakeFiles\gemrb_core.dir\ /FS -c ..\..\..\gemrb\core\Animation.cpp
B:\msvc\src\chiv\gemrb\core\Holder.h(76): error C2027: use of undefined type 'GemRB::GUIFactory'
  B:\msvc\src\chiv\gemrb\core\Interface.h(78): note: see declaration of 'GemRB::GUIFactory'
  B:\msvc\src\chiv\gemrb\core\Holder.h(72): note: while compiling class template member function 'GemRB::Holder<GemRB::GUIFactory>::Holder(const GemRB::Holder<GemRB::GUIFactory> &)'
  B:\msvc\src\chiv\gemrb\core\Interface.h(819): note: see reference to function template instantiation 'GemRB::Holder<GemRB::GUIFactory>::Holder(const GemRB::Holder<GemRB::GUIFactory> &)' being compiled
  B:\msvc\src\chiv\gemrb\core\Interface.h(335): note: see reference to class template instantiation 'GemRB::Holder<GemRB::GUIFactory>' being compiled
```

To work around this, I looked for where Interface.h was including "Holder.h" and added an include for GUI/GUIFactory.h just before it, and then all those files build.

I just don't know if this is right or not, since there is too much stuff happening here that I don't understand. I did manage to run the game and walk around/use the gui though. (that is, after hacking around the final issue I had)

**Comment by bradallred** [comment]
This seems to be a case of MSVC being MSVC. You shouldn't require the definition of a class to create a pointer of that type (all pointers are the same size). MSVC is being lazy and not noticing that `Holder<GUIFactory>` doesn't require the definition for this reason; it just sees we are instantiating a template with the `GUIFactory` type and bailing out because it doesn't know the definition for `GUIFactory` even tho it doesn't need it at this point.

I don't have a problem with moving the include to appease MSVC, but you should remove both the `#include` from `interface.cpp` and the forward declaration of `GUIFactory in `interface.h`

**Comment by chilvence** [comment]
Does this look correct? 

https://github.com/chilvence/gemrb/commit/16f5b77283a986d91be5ddad906fe79fabeb82a4

It builds those files still, but I have removed my awful hack to avoid the other issue so I can't test it yet.

**Comment by bradallred** [comment]
yup, that looks good to me

**Comment by chilvence** [comment]
Nice, one more to go
