### ISSUE TITLE
Subviews & MSVC : CopyColorRange & ColorPal templates

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#767]
This is the final error I have when using MSVC to compile.

It affects 5 files: CharAnimations.cpp, ScriptedAnimation.cpp, WorldMap.cpp GUIScript.cpp and Palette.cpp

```
B:\msvc\src\chiv\gemrb\core\Palette.cpp(122): error C2664: 'void GemRB::Palette::CopyColorRange(const GemRB::Color *,const GemRB::Color *,uint8_t)': cannot convert argument 1 from 'std::_Array_const_iterator<_Ty,16>' to 'const GemRB::Color *'
          with
          [
              _Ty=GemRB::Color
          ]
  ..\..\..\gemrb\core\Palette.cpp(122): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  ..\..\..\gemrb\core\Palette.cpp(52): note: see declaration of 'GemRB::Palette::CopyColorRange'
```

full output: https://pastebin.com/PnABG6tL

I don't know if this has a good clue, but this is the in editor feedback:
![pallette cpp 122](https://user-images.githubusercontent.com/1923867/83320125-481fc300-a23c-11ea-9262-3ed7475740c6.png)

I will keep trying to make it work, but this is well beyond my really limited understanding of C++. If anyone has any hints, I'm totally stumped. 

It looks like it cant figure out the ColorPal template properly though?

**Comment by MarcelHB** [comment]
What about `pal16.data()` or `&pal16[0]`?

**Comment by chilvence** [comment]
I'm kicking myself for not trying that, if I change every instance of pal16.begin() to &pal16[0] etc, then it builds and I can get in game. 

Unfortunately I think that is not the end of that, since I have to explicitly set the size of the palette range to copy, I think the point of using begin() and end() here was to avoid having to do that?

**Comment by MarcelHB** [comment]
If you have contiguous memory, you can provide both `begin/end()` as well as `&[0]/&[0+n]`. Reason is that the underlying `std::copy` is likely taking anything templated that adheres to some arithmetic operators and dereferencing (duck typing). Both pointers and usual iterators, well, know how to do basic `*`, `->` and `++`.

If it's non-contiguous or something different, then `begin/end()` abstract the underlying stuff away, e.g. linked lists, maps, ...

In this case, you can do it by templating the `CopyColorRange` into iterable parameters, and then you should be able to both use pointers and iterators for the reasons above. Or you exploit the fact that you have an `std::array` and use memory addresses that you can use with the signature.

**Comment by bradallred** [comment]
I don't understand how MSVC can claim to be standards compliant here... maybe its because 2 different forms of iterators are being used and maybe that is undefined.

> Unfortunately I think that is not the end of that, since I have to explicitly set the size of the palette range to copy, I think the point of using begin() and end() here was to avoid having to do that?

What do you mean? You specify the range with the iterators, the last parameter is the _destination_. Both of @MarcelHB suggestions are valid for the beginning when the beginning is just `array.begin()`.

> (edit: just noticed, the particular line in the image above doesn't use pal32.end(), but some areas do, eg CharAnimations.cpp line 398)

that's because we don't always want to copy the entire palette.

**Comment by chilvence** [comment]
I may have just been misreading the intent.  Since I only ever end up scan reading random parts of the code, I'm never entirely sure what is supposed to be going on...

I was wracking my brains trying to figure out what it was about this that gcc was fine with but msvc wasn't. Using pal32[32] as the end of the range let me play the game without clown colours though, so I kind of thought 'mañana' to that...

Glad you can see what the issue was though, I'm still having a hard time even though you've both explained it to me :)

**Comment by bradallred** [comment]
Not to dive too deep into technical details, but this actually isn't a _compiler_ issue. It's a stdlib issue. Both libstdc++ and libc++ define `std::array::iterator` as a _pointer_ where the MSVC stdlib (I don't know its name) clearly defines it as some template object. All 3 compilers would produce errors when using a library that doesn't define the iterator as a pointer. The error was mine because the standard does not specify how `std::array::iterator` must be defined. 

The best solution is to use `&pal16[0]` instead of `array.begin()`. Any place we are doing `array.begin() + int` needs to be `&pal16[int]` instead. The same thing applies to the use of `array.end()`.

**Comment by chilvence** [comment]
Still, you'd have hoped that they would all get together and agree on doing things the same way.


...sorry, I have no idea what I was thinking, that would be crazy :)

**Comment by bradallred** [comment]
The "they" in this scenario is the C++ standards committee and they rarely, if ever, define how things are to be implemented. I was the one that didn't follow the standard (I was relying on an implementation detail), which will always come back to bite you in the end.

**Comment by bradallred** [comment]
@chilvence were you going to put together a PR for this?

**Comment by chilvence** [comment]
I have a feeling you might have a much better idea of what do do here than I do :)

I can upload what I have, I do have something that builds based on the conversation above, but I am not convinced I have it totally correct, I'm still not really sure what the different palettes are for and what sizes they should be for instance. I even found a comment that suggests PST has different rules even with this, which makes me even less sure what to do...

**Comment by MarcelHB** [comment]
Just open a PR and we'll comment.

**Comment by chilvence** [comment]
After losing another few arguments with 'vim':

https://github.com/gemrb/gemrb/compare/subviews...chilvence:subviews-msvc-palette-tweaks

**Comment by bradallred** [comment]
I think you need to open a PR for me to actually comment on it

However, everything looks good except for this:
```
- MapIcon->SetPalette(new Palette(colors.begin(), colors.end()));
+ MapIcon->SetPalette(new Palette(colors[0], colors[256]));
```

You are now selecting the wrong constructor: `Palette(const Color &color, const Color &back)` instead of `Palette(const Color* begin, const Color* end)`

That needs to have the addressof (`&`) operator applied.

**Comment by chilvence** [comment]
Whoops, that's not actually intentional, I think I celebrated a bit early when the actors stopped rendering in clown colours.

The main thing I wasn't sure about was the ranges... they seemed self explanatory, but I don't get why the paperdolls for instance have 0-12.  The actual numbers I used for those that didn't have them already were just guesses, which doesn't make me feel super confident...

**Comment by MarcelHB** [comment]
Isn't this arrays? Then just use [size](https://en.cppreference.com/w/cpp/container/array/size) if it was meant to go for full range without hardcoding anything.

**Comment by bradallred** [comment]
> The actual numbers I used for those that didn't have them already were just guesses, which doesn't make me feel super confident...

None of the changes in your linked patch have this other than 0 and 256 which is correct. 
I don't see this 12 you are talking about anywhere that changed and it has nothing to do with paper dolls. If you are wondering about the `0x04 + (idx*12)`  then that is just rolling up the destination indices from this portion of `Interface::GetPalette` in master. All the "subpalettes" are apparently 12 colors.

```
//metal
core->GetPalette( (Colors[0]>>s)&0xFF, 12, &col[0x04]);
//minor
core->GetPalette( (Colors[1]>>s)&0xFF, 12, &col[0x10]);
//major
core->GetPalette( (Colors[2]>>s)&0xFF, 12, &col[0x1c]);
//skin
core->GetPalette( (Colors[3]>>s)&0xFF, 12, &col[0x28]);
//leather
core->GetPalette( (Colors[4]>>s)&0xFF, 12, &col[0x34]);
//armor
core->GetPalette( (Colors[5]>>s)&0xFF, 12, &col[0x40]);
//hair
core->GetPalette( (Colors[6]>>s)&0xFF, 12, &col[0x4c]);
```

As to why those indices start at `4` instead of `0` I have no idea. I could see skipping the first index because it is always the color key. Could be its a bug and the `4` is there because a color is 4 bytes and at some point the type of `col` got changed without this being updated. Tho I would suspect we would have heard about it if we had it wrong.

**Comment by chilvence** [comment]
That alright then - this works in practice in game, I just wanted to make sure I wasn't missing any important detail. I've amended it and made a pull request.
