### ISSUE TITLE
[subviews] hotkeys on modals

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#780]
Didn't have internet access last weekend, so I started some thorough testing of ingame bg2 windowry. One thing I kept hitting is problems with closing the top win via hotkeys. It now doesn't close all the subwindows, so you can end up with those still remaining while the main window closed. Sometimes this can cause real problems, eg. in stores. We really shouldn't be closing from anywhere.

Thinking about it, we should probably treat modal windows differently for hotkeys and only allow default/cancel to go through. And textarea keys like pg up/down and the stuff for editables.

**Comment by bradallred** [comment]
modal windows already block key events (including non-global hot keys). the problem is the option window hot keys are necessarily global hot keys so they work no matter what window has focus.

we need a more sophisticated `CreateTopWinLoader`. The current plan for this is to implement the `OnFocusGained` and `OnFocusLost` events (hot topic lately) so that the window is only closed if `TOP_WIN` has focus. Same applies for attempting to open a new `TOP_WIN` (eg if you have inventory open and then hit 'm' for the map) the new top window fails if the current one doesn't have focus (eg some other sub modal window has been opened).

**Comment by bradallred** [comment]
ok, lets see if this covers everything

**Comment by FrElvire** [comment]
Yes it looks good to me.

**Comment by lynxlynxlynx** [comment]
Breakage is averted now, yes. :) The only thing left is that topwindow hotkeys still update the menuwindow focused button:
- r
- customize
- i
- now the inventory button is highlighted
