### ISSUE TITLE
berzerker to mage dual class goes wrong 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#819]
If you go through the process, you end up with a mage X/berzerker 1 instead of the other way around.

Don't know if this combo ever worked properly, but it should be for all fighter -> mage paths, while mage -> fighter probably works. This has all to do with how the levels and class names are stored in the data.

**Comment by Nykakin** [comment]
Experienced the same issue after dualing kensai to a thief.

**Comment by lynxlynxlynx** [comment]
So F/T. Looks like we have a problem with all the normal variants (only a fighter/thief class exists and not the reverse), so either we don't flip them around enough or too much. The relevant code starts in DCMainDonePress of DualClass.py.

**Comment by chilvence** [comment]
I will put #1067 on pause and see if I can figure out what is going on here.

**Comment by chilvence** [comment]
Testing save games in both GemRB and BG2 original, no matter whether I go from fighter to thief or thief to fighter, the resulting order of the level stats is the same, they are in FIGHTER_THIEF order. Same with Mage -> cleric, cleric -> mage, the levels are always stored according to the relevant multi class combination order, IE CLERIC_MAGE.

That appears to be the intention of this part:

https://github.com/gemrb/gemrb/blob/4ae154d6f1a534b6362536a5894729338ae0f414/gemrb/GUIScripts/DualClass.py#L230-L234

The correct 'original class' bit also seems to be set correctly, which is telling the game what the correct active class is, whether 1st or 2nd.

It appears to only break down when kits get involved. The GUICommon.IsDualSwap function is probably to blame -

https://github.com/gemrb/gemrb/blob/4ae154d6f1a534b6362536a5894729338ae0f414/gemrb/GUIScripts/GUICommon.py#L515-L523

Here's a debug output from my Kensai -> Thief attempt

```
[Python]: dualswap multiclass combo:  ['FIGHTER', 'THIEF']
[Python]: baseclass kit id: 3  #Kensai
[Python]: baseclass kitlist value id: 2 #Fighter
[Python]: old kit class:  PALADIN
```

The call here to GetClassRowName literally returns whatever the row of the [classes.2da](https://github.com/gemrb/gemrb/blob/master/gemrb/unhardcoded/bg2/classes.2da) table, rather than looking for the row with the correct original class ID. 

https://github.com/gemrb/gemrb/blob/4ae154d6f1a534b6362536a5894729338ae0f414/gemrb/GUIScripts/GUICommon.py#L407-L420

In the Kensai's case, the class ID the kit derives from is 2 (FIGHTER), so counting the rows down that table from 0, PALADIN is the one it lands on.

Changing the "index" lookup to "class" returns the correct result, because then GetClassRowName looks for the name by the "ID" column in that table instead.

![kensai to thief](https://user-images.githubusercontent.com/1923867/99218557-adf40d00-27d2-11eb-8db7-011126f17739.png)

It seems to boil down to this one line here if you want to test it, but I am still not sure if I also need to change the other call a few lines up as well
https://github.com/chilvence/gemrb/commit/c8efb1aa55c80a267ef3e2a6fe0f57efcf7bbc57

**Comment by lynxlynxlynx** [comment]
Looks fine to me. IsDualClassed always returns indices. Perhaps this if block can be simplified to also use the value from Dual.

**Comment by chilvence** [comment]
Yes, it looks like GetKitIndex returns a row index in kitlist.2da, which is fine to get the parent class id, this is only going wrong because it then tries to use that class id as a row index in classes.2da

That means using Dual[1] should be fine to lookup the class id in kitlist.2da

At least I finally sort of understand the dual class logic :)
