### ISSUE TITLE
[subviews] Can pick up some of the holy PC items in PST

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#841]
#### Bug description

There are some inventory observations in PST that do not match master and I think should be considered broken; when you try a bit, you can completley drop the following holy PC items, including the default weapons that appear when the upgrades are taken:

1. The Touch by FFG (see below)
2. Annah's knifes
3. Morte's teeth

What looks unaffected:
1. The sword of Dak'kon and the ranged weapon of Nordom
2. Minsc and Boo

#### Screenshots

![store](https://user-images.githubusercontent.com/238558/85788214-e6fce980-b72c-11ea-85a0-c7b9130767c4.gif)

**Comment by bradallred** [comment]
Is this different from #804?

**Comment by MarcelHB** [comment]
> Currently it is impossible to drag and drop anything, there may be other glitches too.

First the part sounds like the opposite of this issue, the latter one - sure. The comment of @chilvence to the suggested changes - no idea. Feel free to close if this is related.

**Comment by chilvence** [comment]
I think this is a consequence of the fact that the script displays the fist weapon if no other weapon is equipped, but does not disable the drag handler (I have actually just commited a fix for that in my WIP

Incidentally, I finally realised why I couldn't get the item cycling working again, which means I have a chance to finish these pst GUIINV fixes now (for both branches)

**Comment by MarcelHB** [comment]
Cool, then let's wait for the PR, then we'll check for closing this.

**Comment by chilvence** [comment]
This branch should fix the dragging in general, but I am uncertain about a couple of things

https://github.com/chilvence/gemrb/tree/841-pst-fistweapons-subviews

**Comment by bradallred** [comment]
> the passing of arguments from button controls got changed somewhere along the line?

I'm not sure if this is what you mean, but control callbacks on subviews can take 2 optional parameters. The first is the control that invoked the callback and the second is the "value" of that control.

**Comment by chilvence** [comment]
That's what I thought, I just probably should have focused on that difference first before turning the scripts upside down, hah

Oh well, I fixed lots of other stuff :)

**Comment by bradallred** [comment]
I don't understand the continued use of `GemRB.GetVar ("ItemButton")` that value should be passed directly to the callback

**Comment by chilvence** [comment]
I was just using it as it was in place elsewhere, I didn't really want to start changing anything, just trying to get PST back in synch functionality wise with the other games.

Once that is done, it should be easier to plan for rewrites, since there won't be so many special cases to tiptoe around. I've already had a few ideas myself the last few days, but I'd prefer to focus on things that don't work more than anything.

**Comment by chilvence** [comment]
@bradallred 

> I don't understand the continued use of `GemRB.GetVar ("ItemButton")` that value should be passed directly to the callback

Thinking of this, I was looking at how other buttons trigger events, almost all of them seem to use [Button].SetVarAssoc("Blah", Value), so that's all I have ever really known to use (IE, I basically learned python by hacking GemRB)

Could you possibly give me an example of the way you mean to do it so I can keep it in mind?

**Comment by bradallred** [comment]
I was asking abut things like `slot = GemRB.GetVar ("ItemButton")` because `slot` can be had just by adding it to the parameter list of the callback. just add a second parameter and call it `slot` (or whatever you want).

instead of:
```
def callback():
    slot = GemRB.GetVar ("ItemButton")
...
```

this works now:
```
def callback(button, slot):
...
# now 'slot' is set to the value of the button
```

You still need to use `SetVarAssoc` to actually assign variables/values to controls.

**Comment by chilvence** [comment]
So would that be SetVarAssoc( "slot" , X ), which would get passed to the second parameter?

**Comment by bradallred** [comment]
yes, the `X` in your example would be passed as the second parameter

**Comment by chilvence** [comment]
Thanks, that actually makes perfect sense, I wish I had thought to question it before

"The More You Know" :)

**Comment by lynxlynxlynx** [comment]
So what's left to do here? I can't drag FFG's hand away, Annah's daggers are surely swappable like any other weapon (but I can't remove the fallback "fist" either — same for Morte).

The only thing I noticed is right-clicking on the "fists" errors out:
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/InventoryCommon.py", line 422, in OpenItemInfoWindow
[Python/ERROR]:     item = GemRB.GetItem (slot_item["ItemResRef"])
[Python/ERROR]: TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by chilvence** [comment]
Whoops, apparently I missed that! It's probably trying to do the item info for the empty weapon slot rather than the fist weapon. I'll try and fix this one tonight.

**Comment by chilvence** [comment]
Correct me if I am wrong but I think there is nothing else to fix here.

**Comment by lynxlynxlynx** [comment]
Closing then. :)
