### ISSUE TITLE
Display console history

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#842]
#### Description
<img width="661" alt="image" src="https://user-images.githubusercontent.com/1126744/85957482-e8a3f880-b94a-11ea-956c-7e7d19d1093f.png">

more visual and interactive than just up/down. Also includes the scroll back with the output/error result from the command.

**Comment by bradallred** [comment]
now that we have a way to track enhancements I suppose it is best to open issues when we add one.

**Comment by lynxlynxlynx** [comment]
Why is there an indentation difference between the two pics? Want me to report problems here or in new issues?

On master I do a review every ~100 commits to update NEWS, so for the interim, it's easiest if you just add to the list in #95.

**Comment by bradallred** [comment]
it's just because that's how the `TextArea` code behaves. the dialog options are all indented, but lists are not. eventually I'll just add a separate label for the error text.

you can report issues here and if they are general TA issues or something ill open a new one from the comment.

**Comment by lynxlynxlynx** [comment]
![image](https://user-images.githubusercontent.com/121515/85946060-1afd2800-b942-11ea-9a88-5c432adee2cd.png)
- no print invocation works
- errors in the label aren't cleared on successive commands (here the gps succeeded)

![image](https://user-images.githubusercontent.com/121515/85946121-66afd180-b942-11ea-8e91-745972d78371.png)
- the label placement is confusing — initially it looks like it's at the bottom, but with use, that's not true any more
- in this case I suspect it's overlaid over a history item, since up/down cycles 3 (not 5!?) items, but I can see only 2 highlight

Inputting numbers doesn't cause errors.

Sometimes I managed to make backspace stop working or worse, but no clear reproducer yet. I also noticed the errors aren't printed to the msgwin if MessageWindowDebug(1) was called before.

I think it would be cleaner if we added a scrollbar to the console text area and not bother manually listing all history. Basically more closely emulating the python shell, which would also obviate the need for a separate error label.

**Comment by bradallred** [comment]
> I think it would be cleaner if we added a scrollbar to the console text area

all `TextArea`s automatically have a scrollbar when needed. increase the number of items beyond 5 and you will see it.

> Inputting numbers doesn't cause errors.

this isn't an error in Python

**Comment by bradallred** [comment]
`print` statements can't run because they don't work in `eval`. I did import the print function from future so you can use that instead. this is what we want anyway as print statements are removed from Python 3 anyway.

**Comment by lynxlynxlynx** [comment]
Much better. I guess the easiest way to make the three sections look distinct is to create a CHU with some rudimentary graphics? We have a fixed size, so it should be easy. I tried first with just setting the bg color of the elements, but that mostly failed.

I found a reproducer for the limited history choice; it has to do with repeated entries / editing them.
1
2
3
4
5 (to fill it up), notice up/down scrolls through all
2
edit last 2 to 4
up/down is then limited to last two entries

**Comment by bradallred** [comment]
yeah, a CHU would be nice at some point when we are sure of the result we want. I have a TODO for moving the control setup to Python which would be cleaner if we had one.

I'm still working on a "shortcut list" of sorts that I might need to optionally depend on iesh for. My goal is to be able to just click on an option from a repopulated list of commands then at a minimum have the cursor positioned correctly to type in the parameters, or even better choose from a list.

for example: one of the first choices might be "Create Item" so you click that then are presented with a list of ITEM codes with their name. which you can click and it will execute the command to create that item. This is what I think you probably need iesh for.

**Comment by lynxlynxlynx** [comment]
To me it sounds like overkill, since even I use it rarely for other things than mta(). The main problem with iesh is that loading all resources takes quite some time. The [list](https://gemrb.github.io/GUIScript/Functions.html) of commands is too big to list and while a proper shell with tab completion could be useful, it still feels like overkill if it doesn't simplify everything (I keep thinking of Quake-like dropdown consoles).

**Comment by bradallred** [comment]
I need it for creating items all the time and I hate having to hunt down item codes. I just wanted a small list of common commands used in testing like "move to area", "create item", "give gold", "give xp", etc.

I've never used it so I didn't realize it was slow. probably not worthwhile and I don't even know if it would be easy to integrate.

**Comment by lynxlynxlynx** [comment]
Well it has to read in chitin.key, check what's overriden in override, then load everything if you want anything more than filenames.

How about repurposing GUISTORE::IdentifyWindow (a bit narrow)? You get plenty of buttons, the input can be done in the window title and the textarea is already there. For some games the journal window would also work, but it's too simple in bg1.

btw, pst already has a little cheat dashboard window, the rest just the input one iirc.

**Comment by bradallred** [comment]
any chance somebody wants to just create us our own CHU? it would be nice to get the GUI into Python and that seems like the easiest way to accomplish that. We can create and layout everything manually in Python like we do in C++ now too, but the simpler the better. This will also keep things consistent for all games and allow us to customize to our needs.

the CHU needs a couple of `TextArea`s some `Label`s and probably a simple background (or not). no need for scrollbars. We can just swap out a regular `IE_GUI_EDIT` with the Console in Python like we do with the maps currently.

**Comment by lynxlynxlynx** [comment]
Sure, that's easy to do. Where do you want the labels? I can see one would be helpful for "History", but I don't know what you need the rest for.

**Comment by lynxlynxlynx** [comment]
You can play with that. Textedit above a textarea above a label above a textarea above a label.

**Comment by bradallred** [comment]
one for history is plenty thank you :)

**Comment by bradallred** [comment]
that seems to work, but I haven't tested much

**Comment by lynxlynxlynx** [comment]
It still has problems with history/focus, like before. For me also the autoscrolling of the output smears when drawn, until a successful command is entered, upon which time it resets to normal. The history list always looks fine.

**Comment by bradallred** [comment]
is that actually new tho?

**Comment by lynxlynxlynx** [comment]
I don't remember. This is on SDL2.

**Comment by bradallred** [comment]
I dont see any previous mention of a focus problem

**Comment by lynxlynxlynx** [comment]
Click on a history entry and scroll up/down with the keyboard.

**Comment by bradallred** [comment]
let me know what you think of that.
