### ISSUE TITLE
[subviews] formation placement regression

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#863]
The new formation placement can be unexpected, to say the least, far into inaccessible parts of areas. These are from ar0205, pivoted in front of the party:
![image](https://user-images.githubusercontent.com/121515/87198513-0eda7880-c2fb-11ea-89a1-b84fbd0996e2.png)
![image](https://user-images.githubusercontent.com/121515/87198652-1d289480-c2fb-11ea-9096-9860bdde83f9.png)
![image](https://user-images.githubusercontent.com/121515/87199552-7264a600-c2fb-11ea-8aad-43df263fe0ba.png)

Expectations:
- not targetting unreachable space (GetBlocked can be used to test the searchmap)
- preferring group cohesion to formation faithfulness (perhaps limiting the point displacement would be enough)

**Comment by bradallred** [comment]
I haven't changed anything about how we determine the valid space, so this can't be a regression. it still uses `area->GetCursor(dest) == IE_CURSOR_BLOCKED` and I believe this is because otherwise you could infer information about unrevealed areas so you shouldn't actually use the search map without also making sure the area is also revealed.

limiting the search distance and maybe reducing the radius would probably keep the group together better. If we hit the distance limit then we can just rotate the vector by some amount and search again and repeat the process till we eventually find a valid point or in the extremely unlikely circumstance we find nothing we just use the last formation point and let the actor figure it out.

**Comment by lynxlynxlynx** [comment]
It is a regression — doesn't happen on master. Perhaps from before yesterday's changes, but I haven't really tested gameplay on subviews before.

**Comment by bradallred** [comment]
The code on master uses `map->GetCursor(p) == IE_CURSOR_BLOCKED` too. The difference is that `Map:: AdjustPosition` uses `GetBlocked`, but for the reason I mentioned it shouldn't do that. I'm pretty sure the originals don't leak information below the fog of war this way either.

Why is it a problem anyway? When we create the path the end node should be unreachable and adjusted or abandoned when the last reachable point is hit.

**Comment by lynxlynxlynx** [comment]
You can't order movement to areas under fog of war any way, so that's not much of a problem — you can just combine the checks (Map::IsVisible to check for the explored part).

It looks bad and doesn't match the originals. They squished the formation if needed, never expanding it.

**Comment by bradallred** [comment]
I was asking specifically about movement commands to unreachable areas, not the formation issue. I know that is a problem and we can do better than "squishing" it which has its own issues with the pathfinder (maybe not with the new one?).

You _can_ order movement under fog on master by rotating to formation. In fact this "regression" _is_ reproducible on master, it's just not as obvious because of the use of `AdjustPosition`. 

So are we in agreement that we consider unexplored areas unreachable entirely for the purposes of formation plotting? This means that we would reform to conform to visible areas even if the unexplored point is reachable. Sound good?

**Comment by lynxlynxlynx** [comment]
No, master has that leak bug, not this regression — it never elongates formations. But whatever, it looks fixed now. I got one crash while testing, but that's likely something else. I couldn't retrigger it and wasn't in a debugger.
