### ISSUE TITLE
Severed Hand opening cutscene doesn't end 

### ISSUE THREAD

**Issue by fizzet** [gemrb/gemrb#893]
#### Bug description
The cutscene when arriving at the Severed Hand (AR5000) does not finish. This might be related to the pathfinder changes because this is the only (and recurring) console output:

[FindPath/DEBUG]: s = (727, 491), d = (751, 523), caller = Larrels Gesandtes Ich, dist = 0, size = 2

**Comment by fizzet** [comment]
Switching back to before the pathfinder merge the cutscene concludes normally.

In particular, it looks like the `MoveToPoint([751.523])` from shlarct1.bcs never finishes.

**Comment by lynxlynxlynx** [comment]
Interesting. He makes several steps just fine, then ends at [727.491]. I wonder if that squirrel is blocking his path. Investigating further ...

**Comment by lynxlynxlynx** [comment]
Heh, in true iwd fashion, the squirrel is immortal. Should still be able to get closer though:
![image](https://user-images.githubusercontent.com/121515/89129115-f4ab4900-d4fa-11ea-80f8-1b918b137050.png)
In the original, he gets to the iron peg part of the draw bridge.

And yeah, it's the squirrel's fault. DoStep lookahead is perhaps too big for it and then Larrel's apparition ends up in a backoff loop. One more for you @kmfrick. It's enough to mta to ar5000, but best results if you do it while paused and then immediately teleport the actor to the bottom right of the map.

**Comment by kmfrick** [comment]
I didn't have the chance to test this yet, I'll get back on a proper computer in the early afternoon. Maybe a `randomBackoff != 0` check should be added to `InMove`? Why do you suggest to check for `oldPos` instead?

**Comment by lynxlynxlynx** [comment]
I was just thinking of how to detect this sort of immobility. The main problem is that the looping happens at all; aborting early would work in this case, where range doesn't matter, but the fact of the matter is that he doesn't move to his target position. And we should fix that.

Checking randomBackoff in InMove could work, but I suspect only if we added another counter and, let's say, returned false after a full round of waiting.

**Comment by neula** [comment]
I encountered exactly the same issue in chapter 6 of BG1, where the party is imprisoned.
The cutscene doesn't work because the area around the prison cell is unwakable (It does work with gemrb commits before the pathfinder upgrade).

**Steps to reproduce:**
- With the provided savegame just wait and select dialog option 2

**Savegame:**

[000000001-cutscene-unreachable.tar.gz](https://github.com/gemrb/gemrb/files/5035892/000000001-cutscene-unreachable.tar.gz)

**Comment by lynxlynxlynx** [comment]
Does applying #894 help with that?

**Comment by neula** [comment]
Sorry forgot to mention that. It doesn't

**Comment by kmfrick** [comment]
Hmm, weird that there are no messages concerning pathfinder failures. It must break earlier.

**Comment by kmfrick** [comment]
It actually breaks on the `prevTicks` check in WalkTo (so good catch about that), _then_, after fixing that, breaks on pathfinding. There was a comment about "we should actually try to reach the closest point to our target", which the old pathfinder, however, did not do. I'll see how the points get adjusted and why it just gets stuck, which _shouldn't_ happen because at some point it must ether run out of points or go over the node limit.

**Comment by kmfrick** [comment]
Good catch about a possible division by zero. Ah, the good old days where such a thing would just bring the whole program crashing down. #894 should have this fixed.

**Comment by lynxlynxlynx** [comment]
The PR doesn't fix this for me, how are you testing it — just getting closer to the squirrel?
