### ISSUE TITLE
 [pathing problem] 2 skeletons at the same place 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#954]
#### Bug description
Here 2 skeletons are at the same place (the right one) so they can't move, as you can see on screenshot below. 

In log : 

[FindPath/DEBUG]: Pathing failed for Skeleton

GemRB version: master

#### Steps to reproduce
1. Enter in cave with provided save
2. Some skeletons are at the same place

#### Screenshots
![skel_same_place](https://user-images.githubusercontent.com/55502325/94993979-f34adb00-0594-11eb-8ba0-7d44be917638.png)

#### Save
[000000015-vos2.zip](https://github.com/gemrb/gemrb/files/5321826/000000015-vos2.zip)

**Comment by lynxlynxlynx** [comment]
I guess they managed to spawn on each other. I'll take a look which action is involved.

**Comment by lynxlynxlynx** [comment]
Ah, it's not related to pathfinding indeed. What happens is that the area comes with a bunch of actors already and then also respawns them via its ini file. So something is wrong or missing there, since there should only ever be one creature per entry, to oversimplify. Eg. "Skeleton 4" and "SKL4".

We read spec_qty, but never use it, so this is it — implement limiting via spec_qty.

**Comment by lynxlynxlynx** [comment]
Turns out the embedded actors don't have their specifics stat set, so even loading the ini later doesn't help. The spec check in the ini thus doesn't get a chance to affect both actors. The only unique thing connecting the pairs is that they have the exact same position, but even that's not true for all pairs.

Looking at original gameplay it does seem like it does spawn all (I count about 20 skeletons of 12+12 expected):
https://youtu.be/2WBq0tzkJEU?t=858
